### ISSUE TITLE
SuperBuild implementation laundry list

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#1]
Things to keep in mind:
- [ ] make sure external ITK/DCMTK/zlib etc are tested, so that it is possible to compile against Slicer
- [ ] should use the same versions of dependencies as in Slicer while doing superbuild to test the same configuration

**Comment by jcfr** [comment]
> make sure external ITK/DCMTK/zlib etc are tested, so that it is possible to compile against Slicer

@fedorov Could you clarify what you mean ?

**Comment by fedorov** [comment]
as you can see from the issue number - this was LONG time ago! I think what I meant is that it would be nice to be able to configure and build with the external libraries. I think this issue at this point can be considered resolved!

**Comment by jcfr** [comment]
> be able to configure and build with the external libraries

Indeed, it is now possible to build by providing any external library. Including JsonCpp itself.

**Comment by fedorov** [comment]
I think the idea for this issue was to keep adding items as I discover them. I don't worry about it now that you are working on the build system.

**Comment by jcfr** [comment]
If needed, you could now adds notes to the "Build System" columns here: https://github.com/QIICR/dcmqi/projects/2
