### ISSUE TITLE
Web page to assist with semantics of the seg object

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#10]
The idea is to take the terminology defined by the standards and constraints to populate this part of the converter parameters:

https://github.com/QIICR/dcmqi/blob/master/doc/dcmqi-itk2seg.json#L41-L82

Reuse the XML files defining the context groups in these files:

https://github.com/QIICR/Reporting/issues/52#issuecomment-137536767

And provide a GUI similar to the one shown here:

https://github.com/QIICR/Reporting/issues/52#issuecomment-154127445

(only the part with the codes selectors)

**Comment by che85** [comment]
We should use 
- Angular Material + Angular JS (https://material.angularjs.org/latest/) for a nice looking UI
- JSON-LD (https://github.com/digitalbazaar/jsonld.js) for JSON validation and
- something for offering options depending on selected codes... (XML library )

**Comment by che85** [comment]
@fedorov I think we should provide a form which allows the user to 
a) Define all series attributes like ReaderID, SessionID etc. 
b) Define segment attributes and have a "+" or "add" button for adding another segment

What do you think?

This is how the current web interface looks like:
![screen shot 2016-06-02 at 10 38 13 am](https://cloud.githubusercontent.com/assets/10195822/15748821/43468dac-28ae-11e6-9c1a-ff47398e8e70.png)

**Comment by fedorov** [comment]
Sure! Good idea. Let's have the first iteration with just one segment, review/merge, and then build extra features?

**Comment by che85** [comment]
Yeah that's exactly what I thought to do

**Comment by fedorov** [comment]
👍
