### ISSUE TITLE
Remove seriesAttributes key from schema, example and converter, web interface

### ISSUE THREAD

**Issue by che85** [QIICR/dcmqi#102]
@fedorov I think we discussed about that in the past. We wanted to remove the seriesAttributes key and have all sub-keys on the same level like segmentAttributes. 

It would look more like:
https://github.com/QIICR/dcmqi/blob/master/doc/pm-example.json
or
https://github.com/QIICR/dcmqi/blob/master/doc/sr-tid1500-example.json

Webapp priority set to low.

**Comment by che85** [comment]
That won't take much time ....

**Comment by fedorov** [comment]
Yes, this is the plan. It is also not good that we have inconsistency in how these attributes are communicated across different types of objects supported. If it won't take much time, please proceed!

**Comment by che85** [comment]
Yes. Same with communicating the compositeContext. Once I am done with this issue here, I will proceed with communicating the DICOM files the same way we do it for the reporting.
