### ISSUE TITLE
Review, revise and cleanup cmake components

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#108]
as discussed with Kitware, the following task needs to be completed:

Simplify build system removing unused macros/functions. System has
been adapted from CTK build system and there is a lot of extra cruft
that should be trimmed down to facilitate the project maintenance.

This task is high priority, since it is a prerequisite for integration of dcmqi in Slicer, which in turn is a prerequisite for the updated Reporting extension, which is in turn is the deliverable that should be completed by mid-November.

**Comment by fedorov** [comment]
@jcfr I talked with @nolden today, and it turns out they already did some work for integrating dcmqi into MITK superbuild. I wanted to make sure these two efforts are connected.

**Comment by jcfr** [comment]
@fedorov Thanks for the note. Update of DCMQI so that it can be build as a Slicer extension is on his way. See https://github.com/QIICR/dcmqi/compare/master...jcfr:update-build-system-and-support-build-as-slicer-extension

**Comment by fedorov** [comment]
Great, thank you for the update! Happy to see progress in this direction.

Just to make sure - after your updates, it will still be possible to build dcmqi standalone independent of Slicer, right?

**Comment by jcfr** [comment]
> it will still be possible to build dcmqi standalone independent of Slicer, right?

Of course, by default it will be standalone package. Then if you even pass `Slicer_DIR` or explicitly enable `DCMQI_BUILD_SLICER_EXTENSION`, Slicer will be expected as a dependency.

**Comment by fedorov** [comment]
👍  thanks for confirming!

**Comment by nolden** [comment]
Currently we patch DCMQI in the MITK superbuild to make SlicerExecutionModel optional:

https://phabricator.mitk.org/diffusion/MITK/browse/T19880-IntegrateDCMQI/CMakeExternals/DCMQI.patch;d888a09319ce1d0dc90c572e798c50cb12849772

So as a feature request, it would be nice to make it optional to build the apps which depend on it

**Comment by fedorov** [comment]
@nolden that's a good suggestion, thank you!

I didn't realize SlicerExecutionModel is not used by MITK?

**Comment by fedorov** [comment]
Build system cleanup PR that has already been integrated: https://github.com/QIICR/dcmqi/pull/111

**Comment by jcfr** [comment]
I see, you basically want to optionally build the library and only have the DCMQI library ? Adding an option named `DCMQI_BUILD_APPS` should be easy enough. Would that work ?

**Comment by fedorov** [comment]
@jcfr from my perspective, this makes a lot of sense, and is also consistent with how things are done in DCMTK.

**Comment by nolden** [comment]
@jcfr `DCMQI_BUILD_APPS` would be perfect!

**Comment by jcfr** [comment]
Closing. This is superseded by #121
