### ISSUE TITLE
Grant access to AppVeyor and CircleCI

### ISSUE THREAD

**Issue by jcfr** [QIICR/dcmqi#113]
@fedorov To facilitate the continuous integration and testing, it would be helpful to have access to the AppVeyor and CircleCI so that I can cancel/restart build.

**Comment by fedorov** [comment]
Sure, but I am not exactly sure where this could be done ...

I've just changed the Appveyor settings as below, but I am not sure if this is is:

![image](https://cloud.githubusercontent.com/assets/313942/20159003/0de3824c-a6ac-11e6-93b0-2a9e4daa5550.png)

For TravisCI, I don't see relevant options in the settings:

![image](https://cloud.githubusercontent.com/assets/313942/20159022/2c27ecb6-a6ac-11e6-8921-c512dc273567.png)

**Comment by jcfr** [comment]
For travis and CircleCI, I am now all set.

For Appveyor, you can add collaborator:  Settings -> Team

In addition, you could also create an "QIICR" account for appveyor, here are the steps: https://github.com/scikit-build/scikit-build/issues/94#issuecomment-234357835

**Comment by jcfr** [comment]
xref #114

**Comment by fedorov** [comment]
I've just added QIICR/dcmqi group to the Appveyor team. Let me know if this worked.

**Comment by jcfr** [comment]
> added QIICR/dcmqi group to the Appveyor team. Let me know if this worked.

Look like I don't have permission to cancel or restart build using the Appveyor interface.

Since Appveyor build are quite fast, this is low priority. There is less of need to cancel and/or restart builds.

**Comment by jcfr** [comment]
Closing, I can now login by selecting the "fedorov" user.

![screenshot from 2016-11-17 00-43-01](https://cloud.githubusercontent.com/assets/219043/20377634/f478c3fe-ac5e-11e6-859a-039f54375d8e.png)
