### ISSUE TITLE
Extension home page

### ISSUE THREAD

**Issue by jcfr** [QIICR/dcmqi#117]
Do you want to create a dedicated page on the wiki: http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/DCMQI

or link to the git book ?

In the mean time, I will use this as a homepage: https://github.com/QIICR/dcmqi#readme

**Comment by fedorov** [comment]
@jcfr I created the wiki page, and I think it makes sense for consistency, but I wonder perhaps extension documentation link should point directly to README, which should be the main entry point (and README points to the the gitbook, which will be populated)?

I don't think it makes sense to duplicate or add extra documentation on the Slicer wiki page. What do you think?

**Comment by jcfr** [comment]
> perhaps extension documentation link should point directly to README

I have no strong feeling, it could easily be change later.

> don't think it makes sense to duplicate or add extra documentation on the Slicer wiki page

It is nice to have it as a entry point that can point the user to relevant resources.
