### ISSUE TITLE
dcmqi Slicer extension packaging fails

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#125]
@jcfr all 3 dashboards fail with the same message - hopefully something easy to fix!

```
 file failed to open for reading (No such file or directory):

    /.../DCMQI-build/dcmqi-build/dcmqi-build/packageupload_cpack_output.txt
```

**Comment by jcfr** [comment]
Should be quite easy. I had only tested doing package locally.
Thanks for the report
Jc

**Comment by jcfr** [comment]
@fedorov After merging this topic, consider updating the ExtensionIndex before 10pm. That way, extension should be available tomorrow.

**Comment by fedorov** [comment]
sure, will do right away. Thank you! 👍

**Comment by fedorov** [comment]
I set revision to master in ExtensionIndex, I think at least for now it makes sense

**Comment by jcfr** [comment]
Makes sense.

**Comment by fedorov** [comment]
@jcfr excellent news - dcmqi is packaged and available in the extension manager today, and things seem to work as tested on mac (I tested with the Reporting extension Christian is working on!). Thank you very much for completing this - now the final stretch - update Reporting extension before the end of this week. 🎆 👍 🎆 

@che85 - another reason that it is time to merge Reporting revision into master and start integrating/testing things with the Slicer dcmqi extension!

**Comment by altazi** [comment]
Hello @fedorov  

I followed all the instructions in this link:

**Comment by fedorov** [comment]
@altazi the dcmqi extension is not intended to be used directly. Instead, it provides converters that are used in the QuantitativeReporting extension, as described in the documentation you referenced.

Maybe if you give more details about what you are trying to achieve I would be able to help better?

**Comment by altazi** [comment]
Hello @fedorov 
Thank you for your response.
my main goal is to export volumes as .DCM from Slicer. 

I am using PET_Tumor_Seg_Effect (Beichel et al) to generate volumes on PET.
my radiomics codes only accepted structures as .dcm. The only method I am able to save is .vtk or .nrrd

Regards,

**Comment by fedorov** [comment]
@altazi thanks for the clarification! For now, I suggest the following steps:

1. Save your segmentation volume in any format such as NRRD or NIFTI from Slicer.
2. Use dcmqi itkimage2segimage command line converter to create DICOM Segmentation object from your segmentation NRRD/NIFTI (you will also need to pass the directory with the source DICOM PET series).

You can find instructions how to install dcmqi and how to use itkimage2segimage converter in the dcmqi guide: https://qiicr.gitbooks.io/dcmqi-guide/

Would this approach work for you? Please let me know if you have any specific problems, or the user guide is not clear.

In the future we will provide the support for directly exporting DICOM Segmentation from the PET segmentation workflow (cc: @chribaue @rbeichel).
