### ISSUE TITLE
Differences in running tests between standalone and Slicer extension builds

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#131]
@jcfr these are located in the bin directory, is this expected?

![image](https://cloud.githubusercontent.com/assets/313942/20324447/a9660b58-ab4e-11e6-8d25-d514c9a7beee.png)

I am investigating why binary tests are not running on dashboards ...

When I build dcmqi as Slicer extension, I am getting this output of ctest:

![image](https://cloud.githubusercontent.com/assets/313942/20324505/dc17a57a-ab4e-11e6-914c-bbc2f723bf7f.png)

The failing tests are expected, since the corresponding cmake was not updated to point to the location of binaries for Slicer extension build.

But while building dcmqi as standalone (not a Slicer extension) the tests other than JSON validators are not running at all:

![image](https://cloud.githubusercontent.com/assets/313942/20324550/0547bd0e-ab4f-11e6-8984-5dd4603f3f0d.png)

**Comment by fedorov** [comment]
Another question - is there a cmake variable that would keep the proper path to the binaries, independently whether they are build in standalone build or Slicer extension build?

**Comment by fedorov** [comment]
Binaries and libraries location for dcmqi standalone build:

![image](https://cloud.githubusercontent.com/assets/313942/20324957/9f058128-ab50-11e6-8a3c-33c246687f8b.png)

**Comment by che85** [comment]
Yes I was just also wondering about the missing tests for the cli executables.

**Comment by che85** [comment]
I guess it has to do with https://cmake.org/cmake/help/v3.0/command/enable_testing.html

**Comment by che85** [comment]
The directory that includes all json schemata/examples specifies the tests in the CMakeLists.txt which is located in the same location as the json schemata/examples. There is no sub directory "Testing" specified.

**Comment by che85** [comment]
Adding 

```
option(BUILD_TESTING "Build Testting" ON)
```

to the CMakeLists in the root directory, builds the tests, but the tests are failing, because the executables cannot be found.

**Comment by jcfr** [comment]
* Location of the CLI test executables should not matter, it currently fails because expression like `${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${itk2dcm}` are used in `add_test`. Using the following `$<TARGET_FILE:${itk2dcm}>`. I will submit a PR.

**Comment by fedorov** [comment]
> Location of the CLI test executables should not matter

@jcfr as I mentioned above, the CLI tests are not even discovered when dcmqi is built as standalone. It is definitely not the issue of not finding the binaries.

I think it is a combination of the issue that @che85 observed and what you are saying - once I comment out `BUILD_TESTING` check, the CLI tests are invoked. What I don't understand is why those CLI tests are running when I build as a Slicer extension - my Slicer build has `BUID_TESTING` set to OFF, and I am guessing it should inherit that variable. Don't understand what is going on. But in any case, I think it makes sense to add the line that @che85 suggested in https://github.com/QIICR/dcmqi/issues/131#issuecomment-260781191.

**Comment by fedorov** [comment]
@jcfr is it expected that `libdcmqi.a` is located in a directory different from other libraries? (see https://github.com/QIICR/dcmqi/issues/131#issuecomment-260774507)

**Comment by jcfr** [comment]
Yes it is for now. This is an optimization that could be done later one.

**Comment by fedorov** [comment]
Thanks for confirming! I consider this resolved for now then.

**Comment by jcfr** [comment]
We basically do not need to package development libraries. Removing the install rules associated with the dcmqi library would be the easiest solution.

**Comment by fedorov** [comment]
indeed, dcmqi packaging will be a good task to have resolved after RSNA! (or before, if time allows and other issues are addressed)
