### ISSUE TITLE
Build issue when git is wrongly configured due to line endings

### ISSUE THREAD

**Issue by CJGoch** [QIICR/dcmqi#14]
I made an error when building dcmqi that might be added to the documentation.

If you experience the following issues when compiling dcmqi:
dcmqi/dcmqi-build/apps/seg/itkimage2segimageCLP.h:214:1: error: stray ‘\’ in program
 {
 ^
dcmqi/dcmqi-build/apps/seg/itkimage2segimageCLP.h:214:3: warning: missing terminating " character
 {
   ^
dcmqi/dcmqi-build/apps/seg/itkimage2segimageCLP.h:214:1: error: missing terminating " character
 {
 ^

This is due to the slicer execution model generating a header file based on a xml with windows line endings on linux.
(In my case due to autocrlf = true instead of = input on linux)

**Comment by fedorov** [comment]
Thanks for reporting!

Thinking about this, it seems that the bug is on the git side, since apparently the setting autocrlf replaces newline incorrectly for your platform. Note that linux CI is working fine on linux: https://circleci.com/gh/QIICR/dcmqi/132 (was, before we introduced the current unrelated bug)

**Comment by CJGoch** [comment]
Actually in this case the bug was on the user side...

For multi-platform projects autocrlf should be "true" on windows and "input" on linux... I just copied the config across operating systems without changing that detail.

So this is more a case of an entry into an FAQ or similar troubleshooting documentation.

**Comment by fedorov** [comment]
ah, yes, this makes perfect sense - thanks!

cc @nolden

**Comment by fedorov** [comment]
This is now captured in a FAQ entry: https://github.com/QIICR/dcmqi-faq/issues/2

@CJGoch I wonder if it makes sense to add these lines to `.gitattributes` of the repository?
```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto
```
this is the suggestion I found here: https://help.github.com/articles/dealing-with-line-endings/
