### ISSUE TITLE
SEG converter does not work properly with multiple input segmentations

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#140]
It looks like the problem is in this line: https://github.com/QIICR/dcmqi/blob/master/libsrc/ImageSEGConverter.cpp#L193. What it should probably do is iterate over all labels that are defined in the segmentation attribute list for the position of the given input segmentation label, and find the item that has labelID matching the pixel value for the current segment in the input segmentation file. If no such label is found, it should fail with error.

**Comment by che85** [comment]
fixed
