### ISSUE TITLE
Adapt converters to use rapidjson

### ISSUE THREAD

**Issue by che85** [QIICR/dcmqi#161]

**Comment by fedorov** [comment]
Let's wait until Slicer+SlicerExecutionModel do the switch. For us this switch is not critical (right?) since there is no performance issue for dcmqi.

**Comment by fedorov** [comment]
Integration of RapidJSON for the Slicer application + terminologies: https://github.com/Slicer/Slicer/pull/646

**Comment by fedorov** [comment]
At this point, I don't even remember why we considered it!
