### ISSUE TITLE
Create packages of dcmqi for all platforms

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#162]
I thought it is good to have it here so that someone interested in the topic can at least know we thought about this....

**Comment by fedorov** [comment]
@jcfr maybe you can give some pointers to @che85 so he can help moving this forward?

**Comment by fedorov** [comment]
@jcfr FYI I create v1.0.0 release and made a note that this is one of the issues that will be addressed in a patch release, see https://github.com/QIICR/dcmqi/releases/tag/v1.0.0

**Comment by jcfr** [comment]
Makes sense.

When you have a chance, would be great to get your feedback on https://github.com/QIICR/dcmqi/pull/188#issuecomment-276619421

**Comment by fedorov** [comment]
This was resolved as of https://github.com/QIICR/dcmqi/tree/v1.0.1
