### ISSUE TITLE
Reorganize doc folder

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#166]
Need to separate schemas, example metadata JSONs, segmentation context JSONS.

**Comment by che85** [comment]
@fedorov Let me know when you are done with that, so that I can apply changes to the web interfaces.

**Comment by fedorov** [comment]
What do you think about the following structure:

```
doc
 \-- schemas
 \-- segmentationContexts
 \-- examples

**Comment by che85** [comment]
Or something like the following. Either way is fine for me.

```
doc
 \-- pm
   \-- schema.json
   \-- example.json
\-- seg
   \-- schema.json
   \-- example.json
...
```

**Comment by fedorov** [comment]
I prefer the first one, since there will be common components of the schema shared across applications.

**Comment by che85** [comment]
Oh yeah that's right. Agreed!
