### ISSUE TITLE
Allow specifying input directory with DICOM instead of list of files

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#182]
It is very inconvenient to specify the list ...

TODO's:

- [x] add checks for duplicates while loading DICOM instances
- [x] revise the implementation to use DCMTK API for parsing the input directory

**Comment by fedorov** [comment]
Anyone has a solution how to get the list of files in directory in C++?!

**Comment by fedorov** [comment]
https://github.com/cxong/tinydir ?

**Comment by fedorov** [comment]
tinydir solution didn't work for me, used the recipe from http://stackoverflow.com/questions/612097/how-can-i-get-the-list-of-files-in-a-directory-using-c-or-c

**Comment by fedorov** [comment]
TODO:

- [ ] add checks for duplicates while loading DICOM instances

**Comment by michaelonken** [comment]
DCMTK has searchDirectoryRecursively(...), [this is the API](http://support.dcmtk.org/docs/classOFStandard.html#23539eec65d0c9a5e896579a2baf9561).

**Comment by jriesmeier** [comment]
There is "now" also a [version of this function](http://support.dcmtk.org/docs-snapshot/classOFStandard.html#a1fae93f115e75ffec0a7dd6829c74a69) that supports wide chars (based on the OFFilename class).

**Comment by fedorov** [comment]
Thank you! I should definitely use this one.

**Comment by fedorov** [comment]
The option has been added.

TODO:

- [ ] revise the implementation to use DCMTK API for parsing the input directory

**Comment by che85** [comment]
@fedorov I am working right now on this issue

**Comment by fedorov** [comment]
Resolved by #196
