### ISSUE TITLE
experiment with alternative bulk file resources for testing

### ISSUE THREAD

**Issue by pieper** [QIICR/dcmqi#19]
As discussed at 2016 summer project week [1] we are looking for ways to be able to test on large collections of DICOM test data.  Previously we have used midas and could also consider using girder or S3.  But as an experiment we are looking at ipfs as mentioned in this comment [2].

Ideal properties for testing data resource:

* reliable and efficient access to the exact bitstream of the test data (confirmed by checksum hash)
* no large external dependencies (ideally just a http download or at most a readily available helper executable)
* scalable to multi-gigabyte or larger test sets covering the range of DICOM data seen in the real world (to allow exhaustive tests, random tests, etc)
* robust in the case of server outages
* peer-to-peer for faster testing when data is already downloaded to other sharing hosts

[1] http://www.na-mic.org/Wiki/index.php/2016_Summer_Project_Week

[2] https://github.com/QIICR/dcmqi/pull/11#issuecomment-227149019

**Comment by pieper** [comment]
There's an experimental pull request: https://github.com/QIICR/dcmqi/pull/22

**Comment by fedorov** [comment]
This is related to #33

**Comment by che85** [comment]
@fedorov Is this issue still up to date?

**Comment by fedorov** [comment]
I think it is safe to close it for now
