### ISSUE TITLE
All tutorial videos are automatically reproduced at the same time

### ISSUE THREAD

**Issue by fepegar** [QIICR/dcmqi#197]
When I go to the introductory tutorial I start hearing 3 Andreys at the same time. I have to navigate through the slides to stop the videos.

http://qiicr.org/dcmqi-guide/tutorials/intro.html

**Comment by fedorov** [comment]
wow, this is terrible! I added autoplay as an adjustment after most of the people looked over the tutorial, and we missed it. Thank you for letting us know! I will disable autoplay until we can figure this out.

**Comment by fedorov** [comment]
Surprisingly, I didn't find an existing issue, so I reported a new one here https://github.com/hakimel/reveal.js/issues/1821

**Comment by fedorov** [comment]
resolved in https://github.com/QIICR/dcmqi-guide/commit/8813c2ed626be71a4ac39933c942b59054eaee25
