### ISSUE TITLE
Creating UML Design for discussion and base for implementation of dcmqi reusable library

### ISSUE THREAD

**Issue by che85** [QIICR/dcmqi#2]
Created a wiki page for this

https://github.com/QIICR/dcmqi/wiki/Design-Decisions

**Comment by fedorov** [comment]
Nice! What tools are you using for this?

**Comment by fedorov** [comment]
Also - how about keeping this under the main repository wiki?

**Comment by che85** [comment]
I am using PlantUML. You can get it as a plugin for CLion. I will move the page to the main repository.

**Comment by che85** [comment]
@fedorov  Seems like I don't have the rights to create wiki pages.

**Comment by fedorov** [comment]
how about now?

**Comment by che85** [comment]
Works. Moved the page to main wiki and updated the issue here.

**Comment by fedorov** [comment]
👍
