### ISSUE TITLE
Add support for conversion to and from DICOM parametric maps

### ISSUE THREAD

**Issue by che85** [QIICR/dcmqi#20]

**Comment by fedorov** [comment]
Sample dataset and JSON added in #24

**Comment by fedorov** [comment]
@che85 can you tell me what is the status of this? is the "writer" ready, or there are things that remain to be done?

by the way, David Clunie told me that OsiriX supports parametric map, so it should be a good experiment to see how it handles our output (whenever it is ready).

**Comment by che85** [comment]
In my opinion it should be ready, but the code needs to be adapted to most recent changes in dcmtk pmap.

I'll create a PR with mentioning the dcmtk pmap working revision.
