### ISSUE TITLE
Add web app for PM converter

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#202]
@che85 now that we have PM context in place, it would be great to add this webapp. Can you walk me over the steps and tools you use to do this? Maybe we can plan to work on this together on Tuesday?

TODO:

- [x] https://github.com/QIICR/dcmqi/blob/master/doc/schemas/pm-schema.json#L75 needs to be a number

**Comment by che85** [comment]
Sure let's do this on Tuesday.
