### ISSUE TITLE
Bad XML for segimage2itkimage

### ISSUE THREAD

**Issue by blezek** [QIICR/dcmqi#230]
The XML produced by segimage2itkimage specifies `outputDirName` with a `channel` of `input` (see the snippet below).  However, as the name suggests, the `channel` should be `output`.  I doubt that this will work inside Slicer.

Can this be fixed?

Thanks,
-dan

```
    <file>
      <name>outputDirName</name>
      <label>Output directory name</label>
      <channel>input</channel>
      <longflag>outputDirectory</longflag>
      <description>Directory to store individual segments saved using the output format specified files. When specified, file names will contain prefix, followed by the segment number.</description>
    </file>
```

**Comment by che85** [comment]
@blezek Thanks for reporting

**Comment by fedorov** [comment]
@blezek thank you for reporting!

I think part of the reason this happened is my lack of understanding of the "channel" semantics. Yes, the purpose of the directory is to store output, but the name of the directory is the input to the converter. So what should I use?

Looking over documentation, this is not clarified (I am not even sure if it should be used for both positional and flag-defined attributes): https://www.slicer.org/wiki/Documentation/Nightly/Developers/SlicerExecutionModel

Looking over examples, here channel is not specified at all: https://github.com/Slicer/Slicer/blob/master/Modules/CLI/CreateDICOMSeries/CreateDICOMSeries.xml#L139

@pieper can you confirm whether `channel` attribute should be used here at all, and whether it should be input or output?

What is wrong however with this argument is that it should be `<directory>`, not `<file>`. I thought I fixed that, but my memory is failing me apparently....

**Comment by fedorov** [comment]
> I thought I fixed that

Never mind - I did fix it here: https://github.com/QIICR/dcmqi/commit/c28309d0bef4570c2538678f8e95a8400bec394b. Looks like you are using an older version of the code @blezek? Where is it coming from?

Also, I forgot to mention it earlier - it works in Slicer both with input and output as the channel ...

**Comment by potis** [comment]
Hi @fedorov we are using version v1.0.4. More specifically we used the linux distribution of the code. 
 https://github.com/QIICR/dcmqi/releases/download/v1.0.4/dcmqi-linux.tar.gz

**Comment by fedorov** [comment]
@potis thanks for confirming. Indeed, this fix was done after v1.0.4. We have docker image for `latest`, but we don't yet have a mechanism to implement automatic generation of binaries for `latest`. We should fix that, and probably make a new release, as it's been over a month since the last one.

@jcfr what is the timeline for adding automatic upload of the packaged artifacts from CI? This was discussed back on Feb 1, but I don't think there was any progress since then: https://github.com/QIICR/dcmqi/pull/188#issuecomment-276619421

**Comment by potis** [comment]
@fedorov  Thanks!

**Comment by blezek** [comment]
Hey @fedorov My memory is fuzzy, but the `<channel>` was supposed to be from the point of view of the CLI program, so `outputDirName` needs to be `output`.  Needs a little more clarification!  I would guess Slicer doesn't care much, because you need to specify a directory both ways.  For [grunt](https://github.com/Mayo-QIN/grunt), we need to know if the user must upload (`input` ) or download (`output`) data from the CLI.

Grunt auto-magickally parses the XML from Slicer plugins to put them in a "web app" or REST microservice.  You can give yours a try:

```
# get the latest grunt / dcmqi docker
docker pull mayoqin/dcmqi

# run
docker run --rm -it -p 9901:9901 mayoqin/dcmqi

# Visit the service
open http://localhost:9901/service/segimage2itkimage
```

Input and output directories end up being zip files, while input and output files are simply uploaded and downloaded.

@potis & @jcfr we could layer grunt on top of your docker, this has been successful for other projects.  We use DockerHub to build all our dockers, works like a charm, as long as they are relatively self contained.  See https://github.com/Mayo-QIN/dcmqi for instance.

**Comment by fedorov** [comment]
@potis we've just released v1.0.5: https://github.com/QIICR/dcmqi/releases/tag/v1.0.5

Sorry for the delay. We plan to have the capability to automatically generate binary packages for the "latest" version of the code automatically for all 3 platforms, at that time the process of preparing releases will be easier (at the moment, I have to manually make packages on all 3 platforms to upload alongside the release!).

**Comment by potis** [comment]
@fedorov thanks for the update!

**Comment by fedorov** [comment]
> You can give yours a try

@blezek just now getting to this. I think this is great and can be very helpful! I've experienced issues with some users being confused by how to run dcmqi converters on Windows, and this can be much better for the purpose of conversion than running CLIs from Slicer interface. Aside from providing a simple GUI to the user, this can also be useful in many other contexts.

One note is that converter is always failing when `outputDirName` is non-empty, and `outputType` must be initialized to the actual value (it is misleading that it shows 'nrrd' hint in the field, but does not ignore the `outputType` parameter when it is not specified.

Great job! We should talk about this at the QIN meeting next week!

**Comment by fedorov** [comment]
p.s. I am sure people asked you about this before, but does your Grunt predates https://gruntjs.com/? The latter is quite well-known. You might consider improving the branding!

**Comment by blezek** [comment]
@fedorov LOL! our `grunt` was completely internal and along the lines of `TACTIC`, `sergeant` and `major`.  We had a military theme going.

Always open to good names

> There are only two hard things in Computer Science: cache invalidation, naming things and off-by-one errors.
> 
> -- Phil Karlton

**Comment by potis** [comment]
@fedorov  @blezek this was a temporary fix (instead of using the CLI we utilized a yml file for the configuration of the service). 

I will update the code based on the newly generated binary files.
