### ISSUE TITLE
Refine parametric map converter schema

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#25]
Missing items:
- image flavor
- pixel contrast

@che85 add items here as you discover them!

**Comment by fedorov** [comment]
@che85 : looking at http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.32.2.html and http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.16.html#sect_C.8.16.1.3, let's have ImageFlavor fixed to "VOLUME".

**Comment by fedorov** [comment]
Should be resolved by #24

**Comment by che85** [comment]
@fedorov I am not sure where the following attributes should go to:

Frame Anatomy Sequence (type 1)
- Frame Laterality (type 1)

Parametric Map Frame Type Sequence (type 1)
- Frame Type (type 1)

Real World Value Mapping Sequence (type 1)
- LUT Explanation (type 1)
- LUT Label (type 1)
- Measurement Units Code Sequence (type 1)

**Comment by fedorov** [comment]
MeasurementUnits are in the schema: https://github.com/QIICR/dcmqi/blob/master/doc/pm-schema.json#L35-L38

LUT Explanation/label are free text - they can be set based on the meaning of the quantity code (if available), or units. We could add it to the schema, but I don't think it is important, and I don't want to have too much stuff there.

Frame type should be easy - they can be copied from the ImageType attribute, and should be in the shared FG:

![image](https://cloud.githubusercontent.com/assets/313942/16522513/669859e6-3f6c-11e6-80c5-f43639477523.png)

So the only one that should be added is anatomy/laterality. Need to think if we could come up with a meaningful default value ...

![image](https://cloud.githubusercontent.com/assets/313942/16522617/fa19fc92-3f6c-11e6-8c56-2041f13fdbe7.png)

**Comment by che85** [comment]
Oh yes I didn't notice that you added MeasurementUnitsCode. I only looked at the example while coding.

**Comment by fedorov** [comment]
Make sure you look at the correct example - it does have units too:

https://github.com/QIICR/dcmqi/blob/master/doc/pm-example.json#L14

**Comment by fedorov** [comment]
I also added the matching nrrd file

**Comment by che85** [comment]
@fedorov MeasurementUnitsCode is missing in pm-example.json

**Comment by fedorov** [comment]
Ah, it's a BUG! This line should be MeasurementUnits, not QuantityUnits!

https://github.com/QIICR/dcmqi/blob/master/doc/pm-example.json#L14

**Comment by che85** [comment]
That should be fixed by now.
