### ISSUE TITLE
Incorrect parsing of the TID1500 SR tree

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#261]
With [this TID1500 SR dataset](https://github.com/QIICR/dcmqi/files/1089635/tid1500sr.dcm.zip), the [output json file](https://github.com/QIICR/dcmqi/files/1089644/m.json.zip) incorrectly contains derivation modifier for Volume measurements.

Command to generate the json from which I took the section below:

```
$ tid1500reader --inputDICOM tid1500sr.dcm --outputMetadata m.json
```

```
                                 {
					"derivationModifier" : 
					{
						"CodeMeaning" : "Standard Deviation",
						"CodeValue" : "R-10047",
						"CodingSchemeDesignator" : "SRT"
					},
					"quantity" : 
					{
						"CodeMeaning" : "Volume",
						"CodeValue" : "G-D705",
						"CodingSchemeDesignator" : "SRT"
					},
					"units" : 
					{
						"CodeMeaning" : "Milliliter",
						"CodeValue" : "ml",
						"CodingSchemeDesignator" : "UCUM"
					},
					"value" : "37.3842"
				},
```

There should be no derivation modifier for Volume measurement. Output of `dsrdump`:

```
 <contains NUM:(,,"Volume")="37.3842" (ml,UCUM,"Milliliter")>
        <has concept mod CODE:(,,"Measurement Method")=(126030,DCM,"Sum of segmented voxel volumes")>
```

Standard deviation appears to be taken from a different part of the tree:

```
      <contains NUM:(,,"SUVbw")="1.73469" ({SUVbw}g/ml,UCUM,"Standardized Uptake Value body weight")>
        <has concept mod CODE:(,,"Derivation")=(R-10047,SRT,"Standard Deviation")>
```

Relevant part of the reader code: https://github.com/QIICR/dcmqi/blob/master/apps/sr/tid1500reader.cxx#L129-L144.

@jriesmeier do you see anything wrong with the code, or is it possible this is a bug in dcmtk?

**Comment by jriesmeier** [comment]
In the referenced code fragment, you only search for child nodes with a concept name of "Derivation", but the "Volume" node has child node with a concept name of "Measurement". Et voilà :-)

I would have further comments on your source code but these would be more "stylistic" ones, e.g. in line 131 you create a copy of the numeric measurement content item... without a need.

**Comment by fedorov** [comment]
> In the referenced code fragment, you only search for child nodes with a concept name of "Derivation", but the "Volume" node has child node with a concept name of "Measurement". Et voilà :-)

Sorry, I don't understand this. Can you explain a bit more? I thought that since I only search for children node of the specific part of the tree with the "Volume" measurement, and it doesn't have a concept name "Derivation", this line https://github.com/QIICR/dcmqi/blob/master/apps/sr/tid1500reader.cxx#L138 should return false. Why does it return a content item at all?

**Comment by jriesmeier** [comment]
OK, now I got it. Sorry for the confusion.

The API documentation of gotoNamedChildNode() says "set internal cursor to a named node (starting from the first children of the current node)." So, basically, it is just an abbreviation of gotoChild() followed by gotoNamedNode(). If you want to search on the first sub-level (direct child) only, you should call gotoNamedChildNode() with the second parameter (searchIntoSub) being OFFalse.

Not sure whether I should make this clearer in the API documentation...

**Comment by fedorov** [comment]
Right, it says "from the first children" (should be child, probably), but the Standard deviation node is not a child node, it is a child of a sibling node. I tried to explain this with the picture attached below. Reading the documentation and your explanation, I still don't understand why it is searching at the levels above the current node. Perhaps I misunderstand where the cursor is at that moment? I thought it is pointing to the node with "Volume" concept.

![img_20170621_114939](https://user-images.githubusercontent.com/313942/27393833-5180ae04-5678-11e7-9167-c5b4b512ccea.jpg)

**Comment by jriesmeier** [comment]
Maybe, the concept of the internal cursor is too simple (but it was introduced already for the initial version back in 2000 when I tried to keep the API as simple as possible, in order to be used via JNI by DICOMscope).

The internal cursor always starts at the root node and each gotoXXX() call iterates over the entire document tree (either starting at the current node or at the root node), i.e. gotoNamedChildNode() first calls gotoChildNode() and - if that exists - calls gotoNamedNode(), which does not only iterate the current subtree but also the following nodes.

A solution would be a new cursor that starts at the root of the subtree (in this case "Volume") and only iterates over all child nodes (in this case there's only a single one). However, this requires to derive a subclass from DSRDocumentTree (see Issue #259).

**Comment by fedorov** [comment]
> each gotoXXX() call iterates over the entire document tree

This is very unintuitive. I would never guess... I think it would make sense to highlight this in the documentation. At least those who read the documentation will have a chance to catch this.

**Comment by fedorov** [comment]
Considering this discussion, I guess it also means that when I search for a node with the "Derivation" concept, I might as well get derivation for a location in a tree somewhere else in this line of code: https://github.com/QIICR/dcmqi/blob/master/apps/sr/tid1500reader.cxx#L138. This is a very critical issue, since this means that potentially the whole JSON output could be completely invalid, as modifiers may not match the concepts they modify in the output.

**Comment by jriesmeier** [comment]
From today's perspective, I agree that the behavior of gotoNamedChildNode() is not very intuitive. The basic idea I had in mind when I implemented it about 1.5 years ago can be read in the commit message:

> Added new helper function gotoNamedChildNode() which sets the internal cursor
> of the document (sub)tree to a named node starting from the first children of
> the current node. This avoid calling multiple other functions and checking of
> return values.

Of course, I could change it and use a local cursor that starts at the first child of the current node and only iterate over the nodes of the corresponding subtree. However, this also means that there would be no gotoNextXXX() for further matches since the local cursor would not exist anymore after the scope of the gotoNamedChildNode() method has been exited.

As a workaround, setting the optional "searchIntoSub" parameter to OFFalse should work in the meantime (see above).

**Comment by jriesmeier** [comment]
In the meantime I further developed the above described idea. A possible solution would look like the following:

```
size_t DSRDocumentSubTree::gotoNamedNodeInSubtree(const DSRCodedEntryValue &conceptName,
                                                  const OFBool searchIntoSub)
{
    size_t nodeID = 0;
    if (hasChildNodes())
    {
        /* start from first child node */
        DSRDocumentTreeNodeCursor cursor(getChild());
        if (cursor.isValid())
        {
            const DSRDocumentTreeNode *node;
            /* iterate over all nodes in the subtree */
            do {
                node = cursor.getNode();
                /* and check for the desired concept name */
                if ((node != NULL) && (node->getConceptName() == conceptName))
                    nodeID = node->getNodeID();
            } while ((nodeID == 0) && cursor.iterate(searchIntoSub));
            /* if found, set internal cursor to this node */
            if (nodeID > 0)
                nodeID = gotoNode(nodeID, OFFalse /*startFromRoot*/);
        }
    }
    return nodeID;
}
```
This should meet your requirements. After some more testing I could commit the changes to DCMTK git repository... but not before the release, which is scheduled for the end of this month.

**Comment by fedorov** [comment]
> As a workaround, setting the optional "searchIntoSub" parameter to OFFalse should work in the meantime

Indeed, this works! I will commit this fix. 

However, it is still very unintuitive. The [documentation for gotoNamedNode](http://support.dcmtk.org/docs-snapshot/classDSRDocumentSubTree.html#acd5d9e2d8a14782d34af7cb6549ed77a) says:

> set internal cursor to a named node (starting from the first children of the current node).

and

> **searchIntoSub** flag indicating whether to search into sub-trees ("deep search") or on the current level only

At least to me, it is not logical that setting **searchIntoSub** to False is required to prevent searching of _the whole tree_!

> In the meantime I further developed the above described idea.

Yes, this should be quite helpful, and the behavior would be logical.

**Comment by jriesmeier** [comment]
The second thing I will do is to remove the optional "searchIntoSub" parameter from gotoNamedChildNode() and set it internally to OFFalse. Of course, also the documentation will be revised.

In fact, when I wrote this method for the SR template support in "dcmsr/cmr", gotoNamedChildNode() was always called with "searchIntoSub" being OFFalse. I guess my idea was that the default value of this optional parameter should be identical to that of other similar methods. But it makes no sense in this context.

Thank you for the report and for the discussion!

**Comment by fedorov** [comment]
Great, thank you Jörg! I am glad we reached consensus, and found both a temporary, and a (hopefully) permanent solution for this problem!

**Comment by jriesmeier** [comment]
By the way, I managed to get the above described changes into the current development version of the DCMTK, i.e. they will also be part of the upcoming DCMTK release 3.6.2.

**Comment by fedorov** [comment]
Excellent news @jriesmeier, thank you!
