### ISSUE TITLE
CircleCI: use pyenv to install python

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#273]
Python install takes very long time on CircleCI.

As noted in this post https://discuss.circleci.com/t/set-python-version-takes-a-weirdly-long-time/5068/5, a better approach could be to use pyenv instead.

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/27798905-1d7905ee-5fe1-11e7-83b2-ae95851b7ba6.png)

**Comment by jcfr** [comment]
Closing. Following the transition to CircleCI 2.0, this not anymore an issue.
