### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#274]
We are considering to switch from the current dcmqi license, which is a copy of the [3D Slicer license](https://github.com/Slicer/Slicer/blob/master/License.txt), to one of the [OSI-approved commercial-friendly licenses](https://opensource.org/licenses).

The motivation for this is that the text of the current license does not really make sense in the context of dcmqi, since it is referring to 3D Slicer. It also makes sense to use a license that is known to reduce the [marginal costs](https://lists.opensource.org/pipermail/license-discuss/2011-April/016997.html) associated with the license.

See related discussion in https://github.com/Radiomics/pyradiomics/issues/268.

The specific alternatives considered are:
- [Apache License 2.0](http://www.tldrlegal.com/license/apache-license-2.0-(apache-2.0))
- [MIT License](https://tldrlegal.com/license/mit-license)
- [3-clause BSD](https://opensource.org/licenses/BSD-3-Clause)

I am gravitating towards 3-clause BSD.

If anyone has thoughts, please chime in!

Special mentions to the people who at this moment contributed to dcmqi: please let us know if you are ok with the change, or if you have any concerns: @che85  @jcfr @nolden @dclunie @msmolens @michaelonken @IlyaFinkelshteyn.

**Comment by dclunie** [comment]
3-clause BSD

David

**Comment by fedorov** [comment]
Anyone has objections to 3-clause BSD?

**Comment by che85** [comment]
It makes sense to switch to another license than the current one. I am fine with switching to 3-clause BSD.

**Comment by fedorov** [comment]
@jcfr @nolden @msmolens @michaelonken @IlyaFinkelshteyn - would be great if we could get an explicit ok re switching to 3-clause BSD from you too!

**Comment by IlyaFinkelshteyn** [comment]
Sure, I kept silence because by contribution was related only to AppVeyor continuous integration issues. But am OK :)

**Comment by jcfr** [comment]
Moving to an OSI approved license is great and  3-clause BSD will work great :+1:  Thanks for checking.

**Comment by fedorov** [comment]
Resolved by #276

**Comment by nolden** [comment]
Sorry for being late ... For the record: 3-clause is fine for me
