### ISSUE TITLE
Update DCMTK to use latest release 3.6.2

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#280]
- [x] make a new binary of DCMTK for Appveyor
- [x] update DCMTK version used in dcmqi superbuild
- [x] update DCMTK version used in Slicer superbuild
- [x] update ExtensionsIndex to use the master branch of dcmqi instead of the custom one that uses the version of DCMTK used currently by Slicer
- [x] do basic tests to confirm QuantitativeReporting is working as expected (after Extension updated in ExtensionManager)
- [x] add a section about updating DCMTK in a (new) Developer section of the user guide

**Comment by che85** [comment]
related to https://github.com/QIICR/Slicer-PETDICOMExtension/issues/7

**Comment by che85** [comment]
related to https://github.com/QIICR/QuantitativeReporting/issues/170
