### ISSUE TITLE
Linking DCMQI to a dynamic library fails on linux

### ISSUE THREAD

**Issue by nolden** [QIICR/dcmqi#301]
If you link the static dcmqi libraries to another dynamic library like a plugin, you get linker errors, like this one: http://cdash.mitk.org/viewBuildError.php?buildid=652980

A proper solution would be a dynamic dcmqi library but that requires symbol export (declspec stuff on Windows ...). For now, I would solve this by adding -fPIC to linux builds which allows for relinking.

**Comment by fedorov** [comment]
xref #303

**Comment by fedorov** [comment]
Closing this, since #303 was merged - @nolden please reopen if the issue is not resolved!
