### ISSUE TITLE
Setting of CXX standard breaks Slicer extension build with C++11

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#307]
Initialization/check of this variable should probably be done such that the variable can be propagated from Slicer superbuild.

https://github.com/QIICR/dcmqi/blob/master/CMakeLists.txt#L9

**Comment by jcfr** [comment]
Closing. I think this addressed by https://github.com/QIICR/dcmqi/blob/58cfd8a3356036b36275cf639e55bb9a6f70e791/CMakeLists.txt#L8-L10
