### ISSUE TITLE
PARSE Error when input dicom folder contains a space character 

### ISSUE THREAD

**Issue by alexisdurieux** [QIICR/dcmqi#308]
PARSE ERROR: Argument: espace/SARCOPAT124/dicom_seg.dcm
             Couldn't find match for argument

`./itkimage2segimage --inputImageList /home/alexis/data/tmp.mha --inputDICOMDirectory "/home/alexis/Documents/test \espace/SARCOPAT124" --outputDICOM "/home/alexis/Documents/test espace/SARCOPAT124/dicom_seg.dcm" --inputMetadata /home/alexis/data/interface.json`

**Comment by fedorov** [comment]
Looks like you did not escape the space in the file name. Can you try renaming the directories to not have spaces (the easiest), or always prepend space with `\`?

**Comment by fedorov** [comment]
It should probably always be

`/home/alexis/Documents/test\ espace/SARCOPAT124`

**Comment by alexisdurieux** [comment]
I tried this but doesn't seem to work eithe

**Comment by fedorov** [comment]
Did you try copying the `SARCOPAT124` into a new directory that doesn't have space in the path? The only explanation I can think of is that the problem is caused by the space in the path.

**Comment by alexisdurieux** [comment]
Sorry for the long response. Yes, If the content is copied into another directory without spaces in its name, it all works perfectly. The space in the path seems to be the trouble maker here. I discovered this while invoking the system call in python and thought it was my path formatting that was the problem. But I managed to reproduce it in terminal. I added quotes but it didn't solve the problem. Did you face or are you aware of a similar issue ?

**Comment by fedorov** [comment]
> I added quotes but it didn't solve the problem. 

@alexisdurieux quotes will not solve the problem. You need to "escape" all special characters, such as space, with the backward slash `\`, like below:

```
$ ls ~/Dropbox\ \(Partners\ HealthCare\)
```

Once you figured out how to do `ls` on that file or folder, it should also work for dcmqi.

**Comment by fedorov** [comment]
@alexisdurieux do you have any updates on this issue? Did you figure it out?

**Comment by alexisdurieux** [comment]
Hey ! I'm so sorry, I totally forgot about this issue. Unfortunately I am no longer working on this project. But if I recall correctly, I did manage to fix it somehow. Thanks for all the hard work you are putting into this library !

**Comment by fedorov** [comment]
Thanks for letting us know!
