### ISSUE TITLE
Add support of TID 4019 Algorithm Identification

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#328]
http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_TID_4019.html

Among other things, this will be, as discussed with @dclunie, the proper approach for distinguishing between the measurements produced by different 3D Slicer Segment Statistics plugins.

**Comment by jriesmeier** [comment]
@fedorov  TID 1419 Row 20 seems to be new in the DICOM standard. If you need support for it in DCMTK's class TID1419_ROIMeasurements_Measurement, please let me know.

**Comment by fedorov** [comment]
@jriesmeier I don't know when it was introduced, I thought it is not so recent. In any case, yes, we decided to use this attribute to encode some measurement-related properties for the measurements produced by Slicer, so I am adding its support.

**Comment by jriesmeier** [comment]
@fedorov I just checked this: TID 1419 Row 20 was added only recently with Supplement 200 (Transformation of NCI Annotation and Image Markup​...). OK, then I'll extend the DCMTK class accordingly (as time permits). I guess that you only need TID 4019 Row 1 and 2?

**Comment by fedorov** [comment]
> TID 1419 Row 20 was added only recently with Supplement 200 (Transformation of NCI Annotation and Image Markup​...).

Makes sense, I didn't realize it!

> OK, then I'll extend the DCMTK class accordingly (as time permits).

If adding this is trivial for you, that would be great, but I am not sure if this is a high priority. There are quite a few items we needed that I added to the converter, algorithm identification is just one of them: https://github.com/QIICR/dcmqi/blob/master/libsrc/TID1500Reader.cpp#L140

>  I guess that you only need TID 4019 Row 1 and 2?

If you add them, I would add row 3 as well. I didn't add it because it is more work, and it was not needed immediately.

**Comment by fedorov** [comment]
Resolved by #329
