### ISSUE TITLE
Selection of platform for hosting test data

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#33]
I keep returning to this issue over and over, and can't make my mind! I don't think there is a perfect solution, but for now I thought I at least document my thinking before choosing something.

# Requirements

* ideally, data and code are versioned together
* should be able to download individual files directly
* bandwidth should be reasonable
* ideally, versioning should be supported
* ideally, user interface (not command line) should be supported for interacting with the data (e.g., data contributors should be able to manage data access)

# Platforms considered

## git-lfs

Pros:
* code and data stay together on github
* versioning

Cons: 
* bandwidth is free only up to some limit
* the only way to download git-lfs managed files is by installing git-lfs, which may be too burdensome for some users

## ipfs, dat

Do not solve the data hosting problem

## Dropbox

Pros:
* bandwidth is great
* user interface for non-developers is great
* direct download link is supported

Cons:
* Dropbox is restricted by some corporate firewalls
* data permanence cannot be guaranteed (subscription, user account inactivity closures)

## Google Drive

Pros:
* bandwidth is great
* user interface for non-developers is ok (not great, since not possible to download folder as zip file)

Cons:
* direct download link is not supported
* may be restricted by some corporate firewalls
* data permanence cannot be guaranteed (subscription, user account inactivity closures)

## Midas

http://slicer.kitware.com/midas3 instance

Pros:
* Free (although, no idea about longevity of the platform)
* direct download links supported
* used by other projects in the 3D Slicer ecosystem

Cons:
* bandwidth is rather poor (download of this dataset takes ~10 min from Midas, and ~1 min from Google Drive on the same network: http://slicer.kitware.com/midas3/item/245513
* experienced problems with using Midas API, not clear if it is supported at all, and by whom (see https://www.kitware.com/midaswiki/index.php/Midas_Server_C%2B%2B_API_and_CLI)

## Girder

https://data.kitware.com/ instance

Pros:
* API exists and should be supported (I have not tried myself)

Cons:
* the instance referenced above does not allow me to create collections (stopper)

**Comment by fedorov** [comment]
> * Midas - bandwidth is rather poor 

TODO: need to test from a non-Partners location

**Comment by fedorov** [comment]
Following the discussion with @jcfr and @pieper, the conclusion was to use Midas for now, with a possible switch to girder in the future....

**Comment by fedorov** [comment]
Midas top-level location: http://slicer.kitware.com/midas3/folder/3771

**Comment by fedorov** [comment]
Immediate needs are met by hosting small datasets on github, and larger ones in Midas. Will revisit later as needed. 

Also note that github is reommends using releases for sharing all kinds of binary data as a workaround, see https://github.com/isaacs/github/issues/712

**Comment by pieper** [comment]
The Releases feature looks like an excellent idea.
