### ISSUE TITLE
SEG related functionality is broken when compiled with C++11

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#335]
The same version of dcmqi, (presumably) built against the same version of DCMTK (with the exception of one extra commit), have different behavior on the same dataset:

![image](https://user-images.githubusercontent.com/313942/36601624-92b20846-1883-11e8-9c3f-e6b40686f82d.png)

The result is that segmentation loaded into Slicer is garbage. below is how it shows up in Slicer, green is the correct segmentation, converted using dcmqi outside of Slicer, and brown-ish is the one converted using dcmqi packaged in the Slicer dcmqi extension.

![image](https://user-images.githubusercontent.com/313942/36602802-ef84229a-1886-11e8-8c46-9dd672bcddc0.png)

* Slicer DCMTK: https://github.com/commontk/DCMTK/commits/patched-DCMTK-3.6.3_20180205
* dcmqi DCMTK: http://git.dcmtk.org/?p=dcmtk.git;a=commit;h=1f20e10ca48ebcbf4cb3e9fd1aae4ce6eaee0609

Test dataset used above is in this PR: https://github.com/QIICR/dcmqi/pull/334

**Comment by fedorov** [comment]
@jcfr @michaelonken any idea what could be going on?

**Comment by michaelonken** [comment]
No idea...

Can you / have you re-build to check this? Maybe one of both projects is pointing in CMake to an old commit? 

Even if the DCMTK version should be different, I am not aware of a bug that would produce this output.

**Comment by fedorov** [comment]
@jcfr is there any chance dashboard can have some residual items from older DCMTK builds? Is it possible to trigger a completely fresh rebuild of extensions?

**Comment by fedorov** [comment]
Trying to reproduce the issue, built Slicer from source, but ran into cmake problems configuring dcmqi extension build (probably related to the changes in this PR https://github.com/QIICR/dcmqi/pull/333#issuecomment-368159023):

![image](https://user-images.githubusercontent.com/313942/36620435-076d9a00-18c1-11e8-8c73-5ddb9d295318.png)

**Comment by jcfr** [comment]
> Trying to reproduce the issue, built Slicer from source, but ran into cmake problems configuring dcmqi extension build

I suspect you tried to reconfigure an existing build tree against Slicer. This is a (rather dumb) sanity check to ensure a consistent set of libraries is used. More details at https://github.com/QIICR/dcmqi/pull/333#issuecomment-368161552

> is there any chance dashboard can have some residual items from older DCMTK builds? 

Slicer based on `master` branch is rebuilt clean every day

Slicer 4.8.1 build tree is kept around to rebuild associated extension daily

> Is it possible to trigger a completely fresh rebuild of extensions?

Extension builds for both SlicerPreview (associated with master) and Slicer 4.8.1 are all done clean every day.

**Comment by jcfr** [comment]
> The result is that segmentation loaded into Slicer is garbage.

Can you confirm that the input given to the CLI is what you expect in both cases ?

**Comment by fedorov** [comment]
Built dcmqi against my local build of Slicer, was not able to reproduce the issue.

> Can you confirm that the input given to the CLI is what you expect in both cases ?

Yes. See screnshots below. Same directory, same input, same arguments, same revision of the source, but different behavior for the binary packaged by the dashboard.

Locally built standalone
![image](https://user-images.githubusercontent.com/313942/36624675-28ca393c-18e0-11e8-9ccd-3d46b3e9d668.png)

Locally built against Slicer
![image](https://user-images.githubusercontent.com/313942/36624682-3a04b0ba-18e0-11e8-8d93-7e62e722dad8.png)

From Slicer nightly dcmqi extension:
![image](https://user-images.githubusercontent.com/313942/36624685-593ef526-18e0-11e8-8210-e369c2331770.png)

Looks like it is failing for any input SEG. You can try it yourself for example with this file: https://github.com/QIICR/dcmqi/blob/master/data/segmentations/liver.dcm

**Comment by jriesmeier** [comment]
@fedorov I haven't checked your code, so this is just a wild guess, but did you check that the DICOM data dictionary is loaded (or built into the executable)?

**Comment by fedorov** [comment]
@jriesmeier no, that should not be the issue - we compile with built-in dictionary enabled:

* while compiling DCMTK within dcmqi: https://github.com/QIICR/dcmqi/blob/master/CMakeExternals/DCMTK.cmake#L92
* while compiling DCMTK as a Slicer dependency: https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_DCMTK.cmake#L95

**Comment by jriesmeier** [comment]
One difference between both DCMTK builds is: for dcmqi shared libraries are disabled and for Slicer they are enabled. Also for dcmqi, DCMTK_FORCE_FPIC_ON_UNIX is set to "ON" (which seems to be a consequence of building DCMTK with static linkage).

By the way, I would also recommend that you explicitly set DCMTK_WITH_WRAP, DCMTK_WITH_ICU, DCMTK_WITH_STDLIBC_ICONV and DCMTK_ENABLE_CHARSET_CONVERSION to "OFF" (if not needed).

**Comment by fedorov** [comment]
Thank you Jörg. Yes, I think we have to build with shared libraries when part of Slicer build. But I can't reproduce this issue when building Slicer and dcmqi as a dependency locally. I will add the flags you mentioned. I think I should also check if this problem happens on Linux and Windows, or if it is a Mac-specific issue, I haven't done that yet.

**Comment by jcfr** [comment]
@fedorov What at the exact step to reproduce the problem ? Something like this would be ideal:

```
./Slicer --launcher-additional-settings /path/to/dcmqi-build/AdditonalLauncherSettings.ini --launch  /path/to/dcmqiprog --param1 ... 
```

**Comment by fedorov** [comment]
@jcfr the steps are even simpler, since it is a CLI and does not need to run via Slicer:
* install dcmqi extension
* run the following command, where `liver.dcm` is [this file](https://github.com/QIICR/dcmqi/blob/master/data/segmentations/liver.dcm?raw=true)

```
/Applications/Slicer.app/Contents/Extensions-26958/DCMQI/lib/Slicer-4.9/cli-modules/segimage2itkimage \
--inputDICOM liver.dcm --outputDirectory .
```

**Comment by jcfr** [comment]
> CLI and does not need to run via Slicer

I think running with Slicer (aka Slicer launcher not Slicer application) is required on windows and linux for **installed tree** to setup the environment. Otherwise, the CLI would not resolve to the expected libraries.

I will post update as soon as I have executed the command

**Comment by fedorov** [comment]
I don't know. My primary system is Mac, and for all the CLIs that I need to use from command line, I don't use the launcher or Slicer application. But I may be wrong. In any case, the error I get on the command line is the same that shows up in the Slicer error log when running the CLI via the application GUI.

**Comment by fedorov** [comment]
Thank you for looking into this JC. I could not join the Slicer hangout today to bring this issue up, and did not have time to investigate further and try other platforms since my last update ... :-(

**Comment by jcfr** [comment]
> My primary system is Mac, and for all the CLIs that I need to use from command line, I don't use the launcher or Slicer application.

Indeed, on macOS, there are no launcher for the installed Slicer. 

> I could not join the Slicer hangout today 

No problem. Also, today, we had the presentation of Dr Chen.

**Comment by fedorov** [comment]
I've just checked with today's nightly on Linux, and it works fine.

**Comment by jcfr** [comment]
Here is what I get trying to run `` using executable built against Slicer:

```
./segimage2itkimage --inputDICOM liver.dcm --outputDirectory .
dcmqi repository URL: git@github.com:qiicr/dcmqi.git revision: 7426ad1 tag: v1.0.9-20-g7426ad1
E: Cannot find Rows or Columns in dataset
E: Rows is not set correctly (0)
E: Columns is not set correctly (0)
Row direction: 1 0 0
Col direction: 0 1 0
Z direction: 0 0 1
Total frames: 3
Total frames with unique IPP: 3
Total overlapping frames: 0
Origin: [-235.2, -226.8, -128.69]
E: Cannot unpack binary frame, invalid input data
Segmentation fault (core dumped)
```

**Comment by jcfr** [comment]
To check that the dataset is not corrupted, here is the checksum of my input data:

```
$ md5sum liver.dcm 
a362ac685eca8dd134ca3cba2dcd510a  liver.dcm
```

**Comment by jcfr** [comment]
For the standalone build, I get the following:

```
./segimage2itkimage --inputDICOM ~/Downloads/liver.dcm --outputDirectory .
dcmqi repository URL: git@github.com:qiicr/dcmqi.git revision: 7426ad1 tag: v1.0.9-20-g7426ad1
Row direction: 1 0 0
Col direction: 0 1 0
Z direction: 0 0 1
Total frames: 3
Total frames with unique IPP: 3
Total overlapping frames: 0
Origin: [-235.2, -226.8, -128.69]
```

**Comment by jriesmeier** [comment]
Are different settings for C++11 support used? I'm asking because I saw that @michaelonken's "dcmseg" code uses C++11 features (if available/enabled).

**Comment by jcfr** [comment]
And yes, when doing standalone build of dcmqi `CMAKE_CXX_STANDARD=98` whereas when it is built against Slicer, it uses `CMAKE_CXX_STANDARD=11`.

I am checking now that if a standalone build done with C++11 fails or not ...

**Comment by fedorov** [comment]
I wanted to understand how this happened. 

Unfortunately, the issue went undetected for such a long time due to several reasons (abbreviated "post-mortem analysis"):
* the corresponding test was failing, and caught this problem immediately on Mac, as soon as the tests were run: http://slicer.cdash.org/testDetails.php?test=8681054&build=1207667 (note that the problem does not show up on Windows: http://slicer.cdash.org/viewTest.php?onlyfailed&buildid=1207972).
* DCMTK was updated not by a PR, but by a direct commit: https://github.com/Slicer/Slicer/commit/0f398d948df6448e32c5b7ad815eded4ad208209#diff-874687e948d17bff029a52cca0cdea93 (I was alerted to it only when @ihnorton added a comment to the issue, because I was watching the repo)
* I believe dashboard started failing first here: http://slicer.cdash.org/index.php?project=Slicer4&date=2018-02-16, but since we have no automatic notifications from CDash, and developers that change Slicer core don't check extensions dashboards after updating the core applications (in part, I guess, because extensions dashboard has a lot of tests/extensions that are always failing)
* Ideally, the build errors in dcmqi (and other extensions that got broken as a result of DCMTK update, which was due to incompatible API) should have been fixed before the update was merged with Slicer master, that way we would detect the regression immediately (as long as we remembered to manually check the extensions dashboard)

Was just thinking what could we do to limit the chances of this happening, and unfortunately it is not as simple as adding a new test. cc: @dclunie since we discussed today on the call how this kind of issue could be avoided in the future.

**Comment by fedorov** [comment]
@jcfr following up on https://github.com/QIICR/dcmqi/issues/335#issuecomment-369117534: I am unable to reproduce this with my local build against Slicer on Mac. Could it be because I built Slicer in Debug mode? I am assuming you tested on mac, since you launched the CLI directly.

**Comment by jcfr** [comment]
> DCMTK was updated not by a PR, but by a direct commit

I think this was discussed during our weekly developer hangout and is part of our effort toward Qt5/C++11. In the future, we will make sure to mention it in the comment and also reference notes on discourse.

> since we have no automatic notifications from CDash

The good news is that CDash support email notification and now support specifying more than one repository. 

We should update the extension build system to ensure the "Update" step is done like for regular project, that way after listing the repository you should get update by email. If you have time to work on this, I could give you some direction.

>  because extensions dashboard has a lot of tests/extensions that are always failing

We should work together to either disable or improve the automated tests and module dependency architecture. This would remove a lot of failing tests.


> Ideally, the build errors in dcmqi (and other extensions that got broken as a result of DCMTK update, which was due to incompatible API) should have been fixed before the update was merged with Slicer master

I agree. We just do not have the resources to do so. Ideally, all extension should be built with any given PR.


> Could it be because I built Slicer in Debug mode?

I do not know.


>  I am assuming you tested on mac, since you launched the CLI directly.

I tested in a build tree on Linux. In that case, there is no need for a launcher

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

$ g++ --version 
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
```

**Comment by fedorov** [comment]
> I think this was discussed during our weekly developer hangout 

If I have a say, I would definitely prefer to see changes like DCMTK version update go through the PR process.

**Comment by fedorov** [comment]
This actually is absolutely needed to address the lack of resources to test all extensions by the core app change contributor. The burden of testing would be shared with the extension developers who are motivated to check the extensions they maintain.

**Comment by fedorov** [comment]
@jcfr I built Slicer on Mac in Release, but failed to reproduce the issue. I don't know what is different between my setup and the one on the dashboard.

Can you let me know how you built/configured Slicer and dcmqi on Linux? When I do default configuration of Slicer, I fail to configure dcmqi:

![image](https://user-images.githubusercontent.com/313942/36866345-0a7cfd6e-1d60-11e8-8c94-236faf889d3f.png)

**Comment by fedorov** [comment]
@jcfr unfortunately #337 didn't resolve the issue. I am now building Slicer against Qt5 on Windows. I also realized that my Mac build was against Qt4, so perhaps that is why I could not reproduce the problem. Many things to try, for sure.

**Comment by fedorov** [comment]
I confirm I can reproduce it on Linux. It happens only when building against Qt5. Same revision of dcmqi and Slicer code built against Qt4 works fine.

**Comment by fedorov** [comment]
Good news! I am able to reproduce the problem in a standalone dcmqi build, when configured with `-DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON `!

@michaelonken any new thoughts in light of this discovery?

@nolden are you building dcmqi with C++11 for MITK? Does that work for you? What version of DCMTK are you using?

I have never tested dcmqi with C++11. I think I should next set up CI to do that.

**Comment by fedorov** [comment]
cc: @ihnorton - would be good to know if switch to C++11 had any effect on the TR support in DCMTK.

**Comment by michaelonken** [comment]
No insights yet but didn't look thoroughly, hopefully on the weekend

**Comment by fedorov** [comment]
@michaelonken here is the minimal example that allows to reproduce the problem independently of dcmqi when C++11 features are enabled in DCMTK with `-DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON`. I built this example against DCMTK compiled in Slicer. Can you take a look?

```
#include <dcmtk/dcmseg/segdoc.h>

int main(int argc, char** argv){

  DcmFileFormat sliceFF;
  sliceFF.loadFile(argv[1]);
  DcmDataset* dataset = sliceFF.getDataset();

  DcmSegmentation *segdoc = NULL;
  OFCondition cond = DcmSegmentation::loadDataset(*dataset, segdoc);
  return 0;
}
```

Result:

```
$ ./segtest ~/github/dcmqi/data/segmentations/liver.dcm                                                                                                  2.3.6
E: Cannot find Rows or Columns in dataset
E: Rows is not set correctly (0)
E: Columns is not set correctly (0)
```

**Comment by jcfr** [comment]
Humm, do you still have a problem if *only* set `-DDCMTK_ENABLE_CXX11:BOOL=ON` without setting `CMAKE_CXX_STANDARD` and `CMAKE_CXX_STANDARD_REQUIRED` option ?

**Comment by fedorov** [comment]
@jcfr indeed, if I *only* set `-DDCMTK_ENABLE_CXX11:BOOL=ON`, it works fine... Did you expect this? Do you know what is the issue?

**Comment by fedorov** [comment]
I am having troubles reproducing the issue. Lost in various configurations, and also not sure if and when cmake behavior varies depending on whether variable is defined in command line vs cmake GUI. I will update the issue with the steps to reproduce once I find my way out.

**Comment by michaelonken** [comment]
I now had time to check the issue in DCMTK, and it appears if compiled with c++11 support enabled. Let me investigate it there before you continue working on it.

**Comment by fedorov** [comment]
@michaelonken any updates on this issue?

**Comment by michaelonken** [comment]
Currently writing :)

**Comment by michaelonken** [comment]
I think I found the issue. Please try fixing two lines in dcmiod's iodimage.h:

Line 275 must read:
typename std::enable_if<DcmIODImageHasType<IODImagePixelModule<T>,Types...>::value,OFCondition>::type

Line 290 must read:
typename std::enable_if<!DcmIODImageHasType<IODImagePixelModule<T>,Types...>::value,OFCondition>::type

The old lines look very similar, though they miss the embracing "IODImagePixelModule" in the template parameter. I will also send you the updated file via mail.

**Comment by fedorov** [comment]
@michaelonken thank you! I confirm this fixes the problem.

When can we expect this patch to be in the public DCMTK git?

When you test DCMTK, do you test with C++11 features enabled?

Do you have a test examining the dcmseg functionality? Even if yes, it apparently didn't catch this issue - would it make sense to add a test to handle it in the future?

**Comment by michaelonken** [comment]
I just pushed it to DCMTK testing, it could be in DCMTK master by the end of the week (if no serious problems pop up on the dashboard).

I have some local tests reading and writing files that are not part of the Dashboard. And yes, those have not been run in C++11 mode so far (the official Dashboards runs C++11 configurations).

I will add something to my tests, and will try to migrate some of the tests into DCMTK upstream so they benefit from the dashboard.

Sorry for the inconvenience. This was was hard to catch.

**Comment by michaelonken** [comment]
I let you know once it's visible on DCMTK master @fedorov .

**Comment by fedorov** [comment]
@michaelonken for now, I made a PR to the fork of DCMTK used in Slicer (by the way, there are 2 extra patches - do you know if those were integrated into DCMTK? https://github.com/commontk/DCMTK/commits/patched-DCMTK-3.6.3_20180205).

> will try to migrate some of the tests into DCMTK upstream so they benefit from the dashboard.

This would be really great!

**Comment by michaelonken** [comment]
The one with isnan/isinf is (C++11-related, too) is already integrated.

The other one  (CMake policy CMP0067) not. I will have a look whether it makes sense to take it over.

**Comment by jcfr** [comment]
For future reference, the change discussed in https://github.com/QIICR/dcmqi/issues/335#issuecomment-373045646 was integrated in our fork of DCMTK as https://github.com/commontk/DCMTK/commit/54004ba20077c626ff4e3042b1d4a5b36eda5e0e available on branch [commontk/DCMTK@patched-DCMTK-3.6.3_20180205](https://github.com/commontk/DCMTK/tree/patched-DCMTK-3.6.3_20180205) and also integrated in Slicer as [r27079](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27079)

> the other one (CMake policy CMP0067) not. I will have a look whether it makes sense to take it over.

I will following on @michaelonken  comments at https://github.com/commontk/DCMTK/commit/88225bc0a3bcaf2d4e4f212522659a06d80ac3bb#commitcomment-28088816

**Comment by michaelonken** [comment]
@fedorov The fix is now available on DCMTK upstream, see commit [b57847](http://git.dcmtk.org/?p=dcmtk.git;a=commit;h=b578472053b8bc7dc926f167bd83ded61376618e) .

**Comment by fedorov** [comment]
Thank you Michael! We should update the CTK fork. But first I want to investigate the issue of inconsistent interpretation described in this PR: https://github.com/QIICR/dcmqi/pull/334, since it could be that will require another fix to DCMTK. I have not made time to work on it yet.
