### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#338]
CircleCI 1.0 is being phased out in the end of August 2018.

Migration guide: https://circleci.com/docs/2.0/migrating-from-1-2

**Comment by fedorov** [comment]
@jcfr do you have any examples of deploy steps for CircleCI 2.0? I am having troubles finding answers in the documentation or on the forum.

**Comment by jcfr** [comment]
To help out I documented and improved the format of the current config. See https://github.com/QIICR/dcmqi/pull/340

Here are examples:
* https://github.com/dockcross/centos-build/blob/master/.circleci/config.yml
* https://github.com/dockcross/dockcross/blob/master/.circleci/config.yml
* https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.circleci/config.yml

**Comment by jcfr** [comment]
To summarize, I envision two `jobs`:
* (1) execution of build/test (and optionally coverage) in a recent Ubuntu image. Build type: `docker`
* (2) generate of `qiicr/dcmqi` image and dcmqi tar.gz package. Build type: `machine`
  * it would be nice to leverage the the [from ... as](https://docs.docker.com/engine/reference/builder/#from) command to implement a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)

**Comment by fedorov** [comment]
Thank you!

Looks like this one is relevant to handle tag-specific deploy tasks: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

**Comment by fedorov** [comment]
Not sure if this is related to a slow phasing out of 1.0, but CircleCI builds started to time out with no significant changes in the code.

**Comment by fedorov** [comment]
@jcfr `docker login -e` has been [deprecated](https://docs.docker.com/engine/deprecated/#-e-and---email-flags-on-docker-login). Can you suggest an update? Can you let me know why that flag was needed/used in the first place?

![image](https://user-images.githubusercontent.com/313942/42183936-a6bab0d8-7e11-11e8-8964-d9fb30efdd00.png)

**Comment by fedorov** [comment]
Remaining tasks:
- [ ] docker image publish
- [ ] codecov
- [ ] release `.tar.gz` package publish on GitHub

**Comment by jcfr** [comment]
That should do it

docker login -u $DOCKER_USER -p $DOCKER_PASS


See https://github.com/dockcross/dockcross/blob/master/.circleci/config.yml
