### ISSUE TITLE
ci_addons packaging script is broken

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#349]
After an unrelated commit, it turns out `ci_addons` stopped working, at least on Appveyor. cc: @jcfr.

Appveyor: https://ci.appveyor.com/project/fedorov/dcmqi/build/0.0.1073

![image](https://user-images.githubusercontent.com/313942/44044410-75dc4960-9ef3-11e8-8d1f-ac3fc7ffa83f.png)

**Comment by fedorov** [comment]
@jcfr thanks for looking into this! 👍

**Comment by jcfr** [comment]
This is fixed by https://github.com/scikit-build/scikit-ci-addons/pull/72, as soon as the associated CI returns green, I will merged and create a new release of the package.

**Comment by jcfr** [comment]
I expect this to be fixed, I re-triggered the build: https://ci.appveyor.com/project/fedorov/dcmqi/build/0.0.1076

If it succeed, I will close this issue

**Comment by jcfr** [comment]
I also re-triggered the build on CircleCI and TravisCI

**Comment by fedorov** [comment]
JC, I reverted that commit, it used a C++11 feature that was failing on some compilers independently from the packaging issue.

**Comment by jcfr** [comment]
Gotcha. I am closing for now. Please, re-open if there are still issues and I gladly fix them.

**Comment by fedorov** [comment]
Sorry, I thought that this packaging issue was independent from the compile error. I will reopen if I see it again. Thanks.
