### ISSUE TITLE
Reorganize dcmqi/gh-pages

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#36]
We should have a top-level page for dcmqi with seg application being a sub-page. 

@che85 - no action for now, let's prioritize when we meet

**Comment by fedorov** [comment]
TODO: add qiicr.org/dcmqi page that has the following:
* one-sentence description of dcmqi (or paragraph from README)(
* pointer to github repo
* pointer to seg application under qiicr.org/dcmqi/seg
* later we will have at least 2 more apps: pm and tid1500

**Comment by che85** [comment]
>later will need to make schema and ld files available under qiicr.org (or maybe better just reference the schema files on github master

@fedorov how would you mention those files? As a table will description and direct link to them or just a link to the github repository directory that holds all json(ld) files?

**Comment by fedorov** [comment]
I think it makes sense to just reference the individual schema files in the master branch, but those references should probably be versioned (specific versions, not just "master" version, should be referenced).

**Comment by che85** [comment]
yes makes sense to me

**Comment by fedorov** [comment]
Resolved via multiple PRs
