### ISSUE TITLE
Incorrect SegmentNumber or ReferencedSegmentNumber should not lead to a crash

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#379]
As identified by @hmeine, inconsistent number assigned to SegmentNumber/ReferencedSegmentNumber can lead to a crash (e.g., one segment starting from 1, but reference containing 0).

**Comment by michaelonken** [comment]
Does that happen in DCMTK? If so, I'll fix it.

**Comment by fedorov** [comment]
@michaelonken thank you! In this case, it was definitely my code to blame.
