### ISSUE TITLE
Library API revision

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#38]
API calls should use in-memory data structures for in/out communication: itkImage and DcmDataset in place of file names

- [x] Change parameters from taking filenames to itkImage and DcmDataset

**Comment by che85** [comment]
@fedorov meta information (JSON) should also be used without using file based in/out communication? If so, I would propose that the CLI executables read files and the API takes a JSON string.

**Comment by fedorov** [comment]
> meta information (JSON) should also be used without using file based in/out communication? 

yes, I've been thinking about this as well. Basically, we need to have a selector between either a file list, or the attributes needed to populate the patient/study/FoR information (and whatever else the import operation needs. But I haven't had a chance to work on it in the schema yet... It is getting more and more complicated ...

> If so, I would propose that the CLI executables read files and the API takes a JSON string. 

yes, or just reads the JSON and passes downstream, if no files are provided.

But now that I am re-reading this, maybe I misunderstood you ... What is unfortunate is that tomorrow I am stuck with meetings until 3pm again, and again won't get to dcmqi.

**Comment by fedorov** [comment]
resolved via #59

**Comment by fedorov** [comment]
parametric map converter API needs updates too
