### ISSUE TITLE
Update to use SNOMED CT codes in place of SNOMED RT

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#386]

**Comment by fedorov** [comment]
Notes for Afshin, who will be using this issue as an opportunity to get started with dcmqi:
* we need to update all occurrences of `(*, SRT, *)` codes to use SCT codes; hard-coded codes are used in the source code, and also in JSON files defining lists of codes
* mapping of codes between SCT and SRT is defined in this part of the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_O.html#table_O-1
* this mapping is also included in this new component of pydicom recently contributed by @hackermd: https://github.com/pydicom/pydicom/blob/master/pydicom/_snomed_dict.py

**Comment by afshinmessiah** [comment]
[Here](https://gist.github.com/afshinmessiah/96f80ec9f5a2ba2cfc96161ae73a4c14) is the list of srt codes that I couldn't find any sct equivalent for.

**Comment by fedorov** [comment]
@afshinmessiah as discussed, let's also see if we can replace instances like this one:

https://github.com/fedorov/dcmqi/blob/master/libsrc/ImageSEGConverter.cpp#L352

`CodeSequenceMacro("121322","DCM","Source image for image processing operation")`

to use `#define`d codes from DCMTK:

http://git.dcmtk.org/?p=dcmtk.git;a=blob;f=dcmsr/include/dcmtk/dcmsr/codes/dcm.h;h=16e3d449ba87f5d6971d695e3511a8c2062c01f2;hb=HEAD#l2397

`CODE_DCM_SourceImageForImageProcessingOperation`

This is less error prone, and more readable/maintainable.

**Comment by afshinmessiah** [comment]
I've also replaced the following srt codes with their corresponding sct (srt:sct) using [this table](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_J.html). Tell me if it doesn't make sense.
srt_sct_tags = {
    'T-9200B': '41216001',
    'T-41070': '7832008',
    'T-48052': '19715009',
    'T-45526': '11279006',
    'D4-31320': '253276007',
    'T-A0193': '128320002',
    'T-47741': '86547008',
    'T-1416B': '53967007',
    'T-41040': '299716001',
    'T-48470': '195416006',
    'R-102BC': '698348000',
    'T-14183': '41313007',
    'T-49423': '714754004',
    'T-4881F': '70253006',
    'T-43126': '91760001',
    'T-4882A': '73931004',
    'T-11500': '421060004',
    'T-4942C': '714759009',
    'T-141A5': '88454005',
    'T-48817': '284639000',
    'T-70010': '431491007',
    'T-40210': '61695000',
    'T-41066': '51114001',
    'T-4806E': '29092000',
    'A-13510': '27065002',
    'T-11167': '13881006',
    'T-48440': '194996006',
    'T-51000': '123851003',
    'T-AB000': '117590005'}

**Comment by fedorov** [comment]
@dclunie this is to follow up on the discussion we had at the IDC call last week. The list of codes that Afshin had troubles matching to SCT is in this reference: https://gist.github.com/afshinmessiah/96f80ec9f5a2ba2cfc96161ae73a4c14. Can you please let us know your suggestion about how to proceed. If the content of that document is confusing, please let me know and I will clarify.

**Comment by afshinmessiah** [comment]
> @afshinmessiah as discussed, let's also see if we can replace instances like this one:
> 
> https://github.com/fedorov/dcmqi/blob/master/libsrc/ImageSEGConverter.cpp#L352
> 
> `CodeSequenceMacro("121322","DCM","Source image for image processing operation")`
> 
> to use `#define`d codes from DCMTK:
> 
> http://git.dcmtk.org/?p=dcmtk.git;a=blob;f=dcmsr/include/dcmtk/dcmsr/codes/dcm.h;h=16e3d449ba87f5d6971d695e3511a8c2062c01f2;hb=HEAD#l2397
> 
> `CODE_DCM_SourceImageForImageProcessingOperation`
> 
> This is less error prone, and more readable/maintainable.
I replaced them. It is just applicable to the set of dcm codes. for sct and ucum, DCMTK doesn't have complete list of macros.

**Comment by fedorov** [comment]
@nolden @emelalkim FYI just so that you know this change is coming, and you can at least think if/how it can affect MITK and ePAD (I don't know if/how exactly ePAD is using dcmqi, but I think at some point it was using it somehow, so just heads up!)

**Comment by dclunie** [comment]
Updated "http://gist.github.com/afshinmessiah/96f80ec9f5a2ba2cfc96161ae73a4c14" as requested

**Comment by dclunie** [comment]
Note that on creation, one should use SCT codes, but on reading, one should be prepared to accept either the old SRT codes or the new SCT codes, otherwise old objects will fail.

**Comment by afshinmessiah** [comment]
> Updated "http://gist.github.com/afshinmessiah/96f80ec9f5a2ba2cfc96161ae73a4c14" as requested

Thank you, David. I've also replaced some deprecated srt code using[ this table](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_J.html), that I'd like to confirm. Is that correct? Look at  my [previouse comment](https://github.com/QIICR/dcmqi/issues/386#issuecomment-580849074).

**Comment by fedorov** [comment]
Another component to this is the webapp that can be used to populate JSON files for dcmqi: http://qiicr.org/dcmqi/. It is built from the [gh-pages branch](https://github.com/QIICR/dcmqi/tree/gh-pages) of the repo, and is using JSON files with the codes from the main repository (see https://github.com/QIICR/dcmqi/blob/gh-pages/js/controllers.js#L24-L28). That webapp should transparently start offering the new codes to the user, but we should confirm this is the case, and it is functional, once the PR is merged.

**Comment by afshinmessiah** [comment]
I need David's help for some other SRT tags[ here.](https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/368#issuecomment-591537489) Sorry for the confusion, I added my question somewhere else by mistake.

**Comment by dclunie** [comment]
Suggested fixes are at https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/368#issuecomment-592070953

**Comment by fedorov** [comment]
Related note from @dclunie re mapping functionality in Pixelmed (email is [here](https://mail.google.com/mail/u/0/#search/david+clunie/KtbxLxgBzCtZrvDsJBsRLWkbkHDsrqTGkg)):

> PPS. You or Afshin may also find the source of ConvertSRTCodesToSCT.java
(which is in the com.pixelmed.apps package) useful, and in particular
the manually created retiredsrtnewsctmapping.xml in com.pixelmed.validate
(as opposed to srtsctmapping.xml, which is generated from Annex O),
though I have not yet released the updates that I provided to Afshin,
which I am experimenting with in the attached file (which is NOT updated
in the current public release).
