### ISSUE TITLE
Superbuild throws error on Ubuntu 18.04

### ISSUE THREAD

**Issue by seandoyle** [QIICR/dcmqi#394]
Hi - 

I just tried building dcmqi (retrieved via ```git clone https://github.com/QIICR/dcmqi.git``` on a new Ubuntu 18.04 machine using the following set of commands:
```
 mkdir dcmqi-superbuild
 cd dcmqi-superbuild/
 cmake /home/sean/Development/github/dcmqi
 make
```
which resulted in the error "Dunno about this gcc":

```[  3%] Building CXX object Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o
In file included from /home/sean/Development/dcmqi-superbuild/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iosfwd.h:8:0,
                 from /home/sean/Development/dcmqi-superbuild/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:27,
                 from /home/sean/Development/dcmqi-superbuild/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/home/sean/Development/dcmqi-superbuild/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:144:4: error: #error "Dunno about this gcc"

Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/build.make:62: recipe for target 'Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o' failed
make[5]: *** [Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o] Error 1
CMakeFiles/Makefile2:650: recipe for target 'Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/all' failed
make[4]: *** [Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ITK.dir/build.make:112: recipe for target 'ITK-prefix/src/ITK-stamp/ITK-build' failed
make[2]: *** [ITK-prefix/src/ITK-stamp/ITK-build] Error 2
CMakeFiles/Makefile2:260: recipe for target 'CMakeFiles/ITK.dir/all' failed
make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

I could build the components by scratch - but if there is something I should try first to debug the issue I'm happy to do it. I believe this is is a mismatch of some sort between ITK and newer versions of gcc.

**Comment by fedorov** [comment]
Most likely, both this one and #396 are due to the fact that dcmqi is using a very old, patched, 4.10 version of ITK. I manually stripped off many components which were not possible to disable via cmake to shorten the build time and meet the CI constraints at the time. Probably the best approach would be to upgrade ITK altogether.

Meanwhile, can you use the binary packages: https://github.com/QIICR/dcmqi/releases/tag/latest? dcmqi is still building fine on all platforms by CI.

**Comment by seandoyle** [comment]
Yes - not  a problem! Thanks.

**Comment by pieper** [comment]
I'd actually leave this open - the underlying issue isn't fixed yet.

**Comment by fedorov** [comment]
Yes, definitely - I didn't mean to imply the issue should be closed.

Sean, would binary packages work to address your immediate needs?

**Comment by pieper** [comment]
FYI - the dcmqi extension is also broken, and that breaks quantitative reporting:
 http://slicer.cdash.org/viewBuildError.php?buildid=1843321

**Comment by fedorov** [comment]
Thanks for the nudge - we fixed dcmqi version to work with the DCMTK pre-updgrade. Once we switch to master, hopefully those errors will go away. I will do this hopefully today once #393 is merged.

**Comment by pieper** [comment]
Sound good - I hope there's an easy fix for the extension.  The build errors are all about things like `CERR` and `COUT` not being defined.

e.g.
`D:\D\P\S-0-E-b\DCMQI\libsrc\TID1500Reader.cpp(21): error C2065: 'CERR': undeclared identifier [D:\D\P\S-0-E-b\DCMQI-build\dcmqi-build\libsrc\dcmqi.vcxproj] [D:\D\P\S-0-E-b\DCMQI-build\DCMQI.vcxproj]`

**Comment by fedorov** [comment]
Yes, those specific errors have already been fixed in master.

**Comment by fedorov** [comment]
I updated ExtensionIndex, let's see tomorrow.

**Comment by fedorov** [comment]
I just realized I didn't update the issue, but the Slicer extension does not have build errors.

**Comment by jcfr** [comment]
Closing. The following pull-request likely addressed the issue:
* https://github.com/QIICR/dcmqi/pull/456
* https://github.com/QIICR/dcmqi/pull/444
