### ISSUE TITLE
Condition failed: Not a directory in ... tid1500writer

### ISSUE THREAD

**Issue by rachit2403** [QIICR/dcmqi#405]
Hello, thank you for the package. Its really good. I do have one error though. I am using docker to run `tid1500writer` , and I obtain this error:
```
dcmqi repository URL: git@github.com:QIICR/dcmqi.git revision: 3efde87 tag: latest-1-g3efde87
Total measurement groups: 2
Adding to compositeContext: 8794971_FLAIR_lesion.dcm
Condition failed: Not a directory in ../../apps/sr/tid1500writer.cxx:68
terminate called after throwing an instance of 'int'
/dcmqi/docker_entry.sh: line 3:     6 Aborted                 $1 "${@:2}"
```

The command I used to get this error is the following: 

```
docker run -v <HOST_DIR>:/tmp qiicr/dcmqi tid1500writer --inputImageLibraryDirectory /tmp/DICOM/ --inputCompositeContextDirectory /tmp/8794971_FLAIR_lesion.dcm --outputDICOM /tmp/DCM_SR.dcm --inputMetadata /tmp/8794971-sr-tid1500.json
```

As you can see my DICOM images lie in tmp/DICOM; the rest reside in /tmp; and I would like to output my structured report into a file name DCM_SR.dcm. 

What do you think could be the issue?

**Comment by rachit2403** [comment]
I have also tried to use the binary package with the command line converters provided in the documentation, this [link](https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.2.2-mac-20200602-3efde87.tar.gz) in particular, as I am using MAC. 

And I obtain a similar error

```
dcmqi repository URL: https://github.com/QIICR/dcmqi.git revision: 3efde87 tag: latest-1-g3efde87
Total measurement groups: 2
Adding to compositeContext: 8794971_FLAIR_lesion.dcm
Condition failed: Not a directory in /Users/travis/build/QIICR/dcmqi/apps/sr/tid1500writer.cxx:68
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6
```

The command I used to get  this error is the following:

```
/Users/rsaluja/<location_to_binary>/dcmqi-1.2.2-mac-20200602-3efde87/bin/tid1500writer --inputImageLibraryDirectory <HOST_DIR>/DICOM/ --inputCompositeContextDirectory <HOST_DIR>/8794971_FLAIR_lesion.dcm --outputDICOM <HOST_DIR>/DCM_SR.dcm --inputMetadata <HOST_DIR>/8794971-sr-tid1500.json
```

`<HOST_DIR>` remains the same in the first comment and the second.

**Comment by fedorov** [comment]
The argument to `--inputCompositeContextDirectory` should be a directory, but it appears that in your case it is a file.

**Comment by rachit2403** [comment]
@fedorov It has started working for both. Thanks for the swift reply.
