### ISSUE TITLE
Segmentation object not released after converting to ITK images

### ISSUE THREAD

**Issue by lorteddie** [QIICR/dcmqi#417]
ImageSEGConverter::dcmSegmentation2itkimage uses DCMTKs DcmSegmentation::loadDataset to parse the dataset into a segmentation object. The resulting object must be freed by the caller but never is, resulting in a memory leak.

Adding the line 
std::unique_ptr<DcmSegmentation> segdocguard(segdoc);
fixes the issue.

**Comment by fedorov** [comment]
@lorteddie thanks for the report - would you like to submit a pull request with the suggested fix?

**Comment by lorteddie** [comment]
ok it took me a while but i think i managed. not sure how to link the pr to this ticket though

**Comment by fedorov** [comment]
@lorteddie thanks a lot for your contribution!

> ok it took me a while but i think i managed. not sure how to link the pr to this ticket though

Next time, you could reference the ticket in the commit message like this `#417`, or you can also link issue to the ticket in the right-hand side ;-)

![image](https://user-images.githubusercontent.com/313942/107425672-44438080-6aed-11eb-8b1c-84b898fea1a7.png)

Thanks again!
