### ISSUE TITLE
Add an option to the SEG web app to support dictionary selection

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#43]
After #42 is resolved

**Comment by fedorov** [comment]
@che85 are you automatically populate the content of qiicr/dcmqi/seg app from json? would it handle multiple segmentation contexts if multuple jsons are found (and allow user to select "Context" by ContextName)?

**Comment by che85** [comment]
right now it handles only one. I need to see how that would look like in order to be able to make the adaptions to the webapp

**Comment by fedorov** [comment]
Next step is for @fedorov to provide more than one example of segmentation context.

**Comment by fedorov** [comment]
@che85 This PR adds another segmentation context. What I propose is the following:

* add a drop-down selector for SegmentationCategoryType that would be populated based on the content of the SegmentationCategoryTypeContextName
* populate the content of Category/Type/Modifier selectors dynamically based on the selected context
* use the same approach for AnatomicRegion/Modifier selectors, with one difference (that I've just discovered today!) - AnatomicRegionModifier section should be disabled when the "showAnatomy" attribute of the selected Category is set to false!  (🎱 FINALLY something that we can use to make the UI simpler, not more complex!!!🎱 )
