### ISSUE TITLE
mac factory build fails because svn not found

### ISSUE THREAD

**Issue by pieper** [QIICR/dcmqi#434]
https://slicer.cdash.org/viewBuildError.php?buildid=2194606

**Comment by fedorov** [comment]
I am pretty sure the check for svn is from some cmake file that is inherited from Slicer. Is svn dependency removed from all places in Slicer and other extensions?

**Comment by pieper** [comment]
Looks good Andrey - I noticed this because I was trying to fix the pet dicom loader so I figured I would report it.

**Comment by fedorov** [comment]
Doesn't look good at all for now, the simple replacement didn't work, I will need to investigate... Thanks for the report!

![image](https://user-images.githubusercontent.com/313942/112908012-c1867d00-90bc-11eb-9670-c4dbd2f3d83f.png)

I should add a GitHub action to scrap the dashboard automatically and update the status in this repo. I never developed a habit of checking the CDash dashboard regularly...

**Comment by fedorov** [comment]
As explained by @lassoan in https://discourse.slicer.org/t/mac-factory-error-svn-error-failed-to-locate-svn/16938, this is a known issue, and errors coming from `computron-macos-tests.kitware` should be ignored.
