### ISSUE TITLE
Fix macos package publishing

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#478]
I cannot understand why, this is happening, but macos package upload errors as below:

<img width="864" alt="image" src="https://github.com/QIICR/dcmqi/assets/313942/01ce1375-486f-4576-a8ac-eab0e10b9e6d">

This is from the failed workflow here: https://github.com/QIICR/dcmqi/actions/runs/6590088040/job/17905966802#step:12:102

This is the corresponding part of the workflow definition:

https://github.com/QIICR/dcmqi/blob/12032e31aeb9c2e4cd9472520d134f7da247909d/.github/workflows/cmake-macos.yml#L99-L106

which is exactly the same as we use on linux:

https://github.com/QIICR/dcmqi/blob/12032e31aeb9c2e4cd9472520d134f7da247909d/.github/workflows/cmake-linux.yml#L46-L56

@jcfr do you have any thoughts on this?

**Comment by michaelonken** [comment]
Maybe the file name with wildcards is not correct and resolves to an empty string. At least I think the error message would look like this. 

I would add a step after the build step which does ls -R on the build directory in order to see whether the ZIP is at the expected position with correct naming.

**Comment by jcfr** [comment]
I will follow-up on this by simplifying the workflow and using current best practices.

**Comment by fedorov** [comment]
@michaelonken note that here: https://github.com/QIICR/dcmqi/actions/runs/6590088040/job/17905966802#step:11:28 it seems to indicate the package name is consistent with the expectations of the wildcard:

> CPack: - package: /Users/runner/work/dcmqi/dcmqi/dcmqi-build/dcmqi-build/dcmqi-1.2.5-mac-20231020-12032e3.tar.gz generated.

**Comment by fedorov** [comment]
Sorry, I didn't realize my comment would close the issue!

**Comment by fedorov** [comment]
No, that didn't fix the issue. @jcfr hope you have ideas what's gong on!

**Comment by michaelonken** [comment]
Another guess:

Multiline separators are missing for this command, i.e. backslashes like in

```
ci_addons publish_github_release QIICR/dcmqi \
    --prerelease-packages "build/dcmqi-build/dcmqi-*-linux-*.tar.gz" \
 ``` 
...

**Comment by fedorov** [comment]
@michaelonken you were right - that was it! https://github.com/QIICR/dcmqi/actions/runs/6598744176/job/17927016620 succeeded!

I thought I specifically looked and made it the same as in linux, but I messed it up!

@jcfr I am closing this one, but if you ever get a chance to review and suggest where best practices can be improved, this would of course be most welcomed contribution!
