### ISSUE TITLE
Fix tagged release creation and package upload

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#482]
Those have been broken since we migrated to GitHub actions :-( Summary below is what I communicated to Vamsi by Discord, but it is better to continue the discussion here for transparency and coordination, so I replicate what I said below.

Some time ago I migrated dcmqi to GA from  Appveyor/TravisCI/CircleCI. That was my one and only major foray into GA. I think I got most of the things figured out, with one exception. We used to have the process where tagged git commits that follow the versioning convention would be uploaded to GitHub and a new release would be created, but that got broken, and I feel it would take me too much time to figure out how to fix it.

The original CI was set up by Jean-Christophe @jcfr from Kitware (whom you will hopefully meet at the project week!), and he used a dedicated python package to handle this, see https://github.com/QIICR/dcmqi/blob/master/.github/workflows/cmake-linux.yml#L60-L65. I think the motivation for that package was to deal with the differences across CI platforms.

Packaging and upload of the "latest" release works fine, but not the tagged releases, which I believe would be handled by this clause in the command: `--release-packages "build/dcmqi-build/dcmqi-*-linux.zip"`

This is the commit that I tagged, which would be expected to generate and upload a release package: https://github.com/QIICR/dcmqi/commit/697ff258b6cc76fcf04d7e1dd35dc67e08f8b857
but it only uploaded latest: https://github.com/QIICR/dcmqi/actions/runs/6671898376/job/18134744092

It may be as simple as the package not assigned the expected file name. As you can see, the package file is named dcmqi-1.2.6-linux-20231027-697ff25.tar.gz, and the release pattern is dcmqi-*-linux.zip.  Which as I just now realize can't be right - it should have tar.gz extension. But it also failed on all other platforms to upload the tagged release package.

The reason I would really like to fix it is because yesterday we merged the dcmqi improvement that speeds up DICOM SEG read by orders of magnitude, and I would want to have a release to make this capability easily accessible ("latest" packages are not persistent, so it makes no sense pointing users to include them into notebooks etc).

**Comment by fedorov** [comment]
I should also correct myself - it was not just me who did the migration to GitHub actions - Michael Onken @michaelonken contributed a lot to this as well, helping fixing bugs and addressing many of the related issues as well! 🙏

**Comment by vkt1414** [comment]
Happy to work on this! I'll first try to troubleshoot with scikit itself. And if you are okay with using github api, you may consider the following.

In a recent workflow, we tried using GitHub API to handle releases with help of a python script [get_latest_index.py](https://github.com/ImagingDataCommons/SlicerIDCBrowser/blob/main/.github/get_latest_index.py#L67-L95) running inside GitHub actions [update_release_attachment.yml](https://github.com/ImagingDataCommons/SlicerIDCBrowser/blob/main/.github/workflows/update_release_attachment.yml).  I also think with the [Matrix approach](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) in GitHub actions, we should be able to build and publish for all three platforms parallelly with a single workflow. Might be worth considering as it may reduce maintenance.

**Comment by fedorov** [comment]
Switching to github API in place of scikit would be completely fine, if fixing the scikit approach is not easy. Using matrix approach is also interesting. The current organization of the workflow is due to the need to support multiple CI platforms before GitHub actions, it was just the most natural first step in migration.

**Comment by vkt1414** [comment]
reading scikit documentation carefully suggests that the reason why the commit https://github.com/QIICR/dcmqi/commit/697ff258b6cc76fcf04d7e1dd35dc67e08f8b857 did not trigger release is because the commit was tagged with v1.2.6 where as scikit expects just 1.2.6 I think..
https://scikit-ci-addons.readthedocs.io/en/latest/addons.html#use-case-automatic-upload-of-release-packages-associated-with-a-tag
![image](https://github.com/QIICR/dcmqi/assets/115020590/e501e7ea-59af-4923-90ca-5e60b867791d)

@fedorov I did not test on my fork yet, will test and report back.

**Comment by fedorov** [comment]
I would be very surprised if that's the culprit. The version tagging has been following the same pattern since the first releases, you can see the tags in https://github.com/QIICR/dcmqi/releases. 

<img width="435" alt="image" src="https://github.com/QIICR/dcmqi/assets/313942/8d1e5aae-a667-4238-8efd-4532b982a39b">

**Comment by vkt1414** [comment]
@fedorov you were right.. tags starting with 'v' were also recognized as released tags.. I found the issue is related to fetching tags in github actions while checking out code. https://github.com/actions/checkout/issues/206
I submitted a PR, as with this PR, it should recognized the tags, but I couldn't check if release attachments are created properly for mac and linux.

**Comment by vkt1414** [comment]
update: I modified some minor changes to expected release file names and everything should now work as expected.

**Comment by fedorov** [comment]
Will close once we confirm it works with a release tag - I will make one soon!

**Comment by fedorov** [comment]
It worked! 🎉 

![image](https://github.com/QIICR/dcmqi/assets/313942/e759d39b-7462-4fb1-bb57-20315d3e8d76)
