### ISSUE TITLE
Fix publishing of docker images

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#487]
This appears to have been broken since 1.2.5.

https://hub.docker.com/r/qiicr/dcmqi/tags

**Comment by fedorov** [comment]
After the commit above, logs say the image is pushed

![image](https://github.com/QIICR/dcmqi/assets/313942/e716eae0-4ac8-4b48-b668-4ebabe82b6ad)

but the latest tag in Docker Hub is still 1 year old! ..

https://hub.docker.com/repository/docker/qiicr/dcmqi/general

**Comment by michaelonken** [comment]
Are you maybe pushing to your private docker org?
(ORG = fedorov in docker/Makefile)

**Comment by fedorov** [comment]
Confirmed the new v1.3.1 release resulted in 1.3.1 docker image upload!
