### ISSUE TITLE
Add an option to pass patient/study/equipment etc via JSON

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#56]
The idea is the following:
- give user an option to either specify source DICOM files to carry forward composite context, or specify individual modules
- when possible, assign default values to allow for conversion even if source data is not available
- to manage complexity, include only attributes listed as Type 1 or 2, skip Type 3 or conditionals

Known deficiency, out of many I am sure, this "parameterization" is lossy with respect to the standard, as it does not communicate modules completely, and does not preserve their definition (Type) completeness. The motivation for this is to reduce complexity, and handle only the attributes that are of interest for the QI applications.

Related to #44

**Comment by che85** [comment]
related to #38

**Comment by fedorov** [comment]
I am thinking to remove this issue from the milestone, and keep the requirement of input DICOM files for now

**Comment by che85** [comment]
Makes sense. I guess that would be much more thinking and work.

**Comment by fedorov** [comment]
a related observation - the way composite context is passed to the converters is different between tid1500, seg and paramap converters; this will need to be fixed.

**Comment by fedorov** [comment]
The essence of this request (passing composite context without having access to a DICOM file containing it) will be addressed by https://github.com/QIICR/dcmqi/issues/390.
