### ISSUE TITLE
Package dependencies for all platforms

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#62]
This would help with reducing time to test pull requests; currently, only appveyor dependencies are packaged (because appveyor's time constraints are most limiting).

**Comment by che85** [comment]
Ownership transferred for dcmtk to https://github.com/QIICR/dcmtk

**Comment by fedorov** [comment]
With the switch to GitHub Actions, and the generous allowances for the workflow time limits, this is not at all a priority right now. We are not even close to hitting the limits to justify investment of effort into this.
