### ISSUE TITLE
Test the seg converter with the NAC brain atlas

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#69]
http://slicer.kitware.com/midas3/item/250727

Error reported by @pieper:

```
Convert DICOM SEG into NRRD standard error:
W: ReferencedPerformedProcedureStepSequence (0008,1111) empty in SegmentationSeriesModule (type 1C)
Failed to get segment for segment ID 4
```

(with Reporting converter, not dcmqi directly)

It is known that the segments are not numbered consecutively for this dataset.

**Comment by fedorov** [comment]
@michaelonken when I am testing dcmqi converter with the dataset referenced above, I am getting this error: https://github.com/QIICR/dcmqi/blob/master/libsrc/ImageSEGConverter.cpp#L552-L556

However, this segment is present in the dataset:

![image](https://cloud.githubusercontent.com/assets/313942/20366792/a4320d04-ac1a-11e6-9cb8-dfce1beb0261.png)

Do you have your dcmtk-only reader test that I could use to see if this is a dcmtk problem? I thought there was one, but I can't find it in the dcmtk build tree.

I also see that segments in this dataset are not numbered consecutively - 378 is followed by 4002, which is a violation of the standard (https://fedorov.cloudant.com/dicom_standard_2015c/.site/chtml/part03/sect_C.8.20.2.4.html), so perhaps that is the problem and dcmtk behavior is as expected?

**Comment by michaelonken** [comment]
I'll check and let you know

**Comment by fedorov** [comment]
@michaelonken sorry - I just now saw this, since you edited an existing comment, and that doesn't trigger a notification!

>  By the way: David has an updated dataset of the atlas that used correct Segment Numbers if I remember correctly.

I know @dclunie has been refining that example, but I am using the latest (as far as I can tell!) version of it from August this year.

> What do you think would be the best approach?

This is tricky. I know David will say we should be able to read anything, but I wonder where is the limit to auto-correction that should be done in dcmtk. I think in this specific situation, what you suggest makes sense to fix. 

I also think that dciodvfy should be fixed to report this problem with inconsistent segment numbering - right now it doesn't detect this problem!

**Comment by dclunie** [comment]
I have extended dciodvfy to check segment numbers. It now reports when:

- they are not monotonically increasing from one by one

- when there are referenced segment numbers for a frame that do not have segment numbers in the segment sequence

See the 2018/06/22 release or later at:

http://www.dclunie.com/dicom3tools/workinprogress/

E.g., for the "seg2013_nac_hncma.dcm" file in question, it now reports:

Error - SegmentNumber not monotonically increasing from one by one - have SegmentSequence item number 2 (from one) with SegmentNumber of 513

**Comment by fedorov** [comment]
On Fri, Jun 22, 2018 at 2:25 PM, David Clunie wrote:

Hi guys

This is an old thread, but I was motivated to produce an
updated brain atlas as a SEG example to provide to Brad
Erickson.

I have finally updated the SEG to correct the problem with
the Segment Number not starting from 1.

See:

  https://www.dropbox.com/s/bk3j3t4wdg3hpe0/seg2013_nac_hncma_20180622.tar.bz2

Also:

  http://slicer.kitware.com/midas3/folder/1927

These replace the 20160817 version.

David

**Comment by fedorov** [comment]
On Fri, Jun 22, 2018 at 2:42 PM, Andrey Fedorov wrote:
Thanks David!

I noticed that

1) not all of the segments have the CIELab color assigned (mostly those around segment 300 have color missing)

2) DimensionIndexValues are not monotonically increasing (e.g., 1/202, 220/202 - looks like they are bunched by the ImagePositionPatient?). Reading the standard, it was not entirely clear what is implied by the following - whether indices should be possible to order into monotonically increasing order, or that they should be stored in monotonically increasing order in the instance ... "Each Attribute referenced in the Dimension Index Sequence (0020,9222) will have an index stored in the Dimension Index Values (0020,9157) for each frame. Each index value is an ordinal number starting from 1 and monotonically increasing by 1 within the scope of a Dimension Organization UID (0020,9164)." (from http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.17.html)

**Comment by fedorov** [comment]
On Fri, Jun 22, 2018 at 3:08 PM, Andrey Fedorov <andrey.fedorov@gmail.com> wrote:
I also noticed that the geometry of the grayscale image and the segmentation matrix is not the same (320x288 vs 256x256).

Aside from those issues, dcmqi converter didn't fail, and after resolving some "issues" ...

 * the conversion is not instantaneous, since it's 300+ segments, and we don't have progress reporting for DICOM plugins in Slicer
 * presence of the "Background" label showing as a black blob was unexpected, had to hide it
 * Slicer is incapable of loading Legacy Converted Enhanced MF MRI, and so I used dcm2niix converter to make nii out of the DICOM grayscale that David provided

... the interoperability of NAC atlas DICOM representation has been established using off-the-shelf Slicer + QuantitativeReporting extension from May 20, 2018, as demonstrated below!

![image](https://user-images.githubusercontent.com/313942/41794864-d2d7b2be-762e-11e8-815a-8a54ad010592.png)

**Comment by fedorov** [comment]
On Fri, Jun 22, 2018 at 3:13 PM, David Clunie <dclunie@dclunie.com> wrote:
> Hi Andrey
>
> 1. Missing colors (and labels) - this is because there are
> label index values present that do not have any description
> in any LUT that was ever circulated - see the attached email
> thread with Marianna regarding this - if there are no colors
> it will; also have a code for "topography unknown"
>
> 2. The DimensionIndexValues should be monotonic from 1 by 1
> within the scope of the entire set of indices for that SOP
> instance ... i.e., the complete set of segments, and the
> complete set of spatial positions; obviously they are not
> necessarily ordered that way for the descriptions of each
> successive encoded frame, or that would defeat their purpose
> of being able to reorder the frames; the whole point is to
> allow a different description of the dimensions than what
> happens to be the encoded frame order ... the sequential
> values of the DimensionIndexValues are the order in which
> one sorts along that dimension (even if you don't
> understand what that dimension "is", e.g. don't know how
> to decipher ImagePositionPatient); the attached slides from
> an old presentation may or may not help.
>
> David

[Pages from NewCTandMRDICOMObjects.pdf](https://github.com/QIICR/dcmqi/files/2128861/Pages.from.NewCTandMRDICOMObjects.pdf)
