### ISSUE TITLE
Add proper testing

### ISSUE THREAD

**Issue by che85** [QIICR/dcmqi#9]
Specific sub-tasks:

Segmentations
- [x]  add test DICOM data and baselines (@fedorov)
- [x]  seg2itk conversion test: confirm the images are equivalent
- [x]  itk2seg conversion test: 
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

Parametric Maps
- [x]  pmap2itk conversion test: confirm the images are equivalent
- [x]  itk2pmap conversion test: 
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

Structured Report
- [x]  tid1500reader test
- [x]  tid1500writer test
  - [x]  run dciodvfy on the output
  - [x]  confirm round-trip test is working

**Comment by fedorov** [comment]
Specific sub-tasks:

1) add test DICOM data and baselines (@fedorov)
2) seg2itk conversion test: confirm the images are equivalent
3) itk2seg conversion test: 
 3.1) run dciodvfy on the output
 3.2) confirm round-trip test is working
