### ISSUE TITLE
Update paramap2itk converter to initialize DWI parameters

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#91]
Writing paramap with DWI parameters was added in #85, but not the reverse.

add the following attributes to meta output:
- [x] 'MeasurementMethodCode'
- [x] 'SourceImageDiffusionBValues'
- [x] 'DerivationCode'

**Comment by fedorov** [comment]
Missing attributes in meta output:
* 'MeasurementMethodCode'
* 'SourceImageDiffusionBValues'

**Comment by che85** [comment]
@fedorov I added checkboxes for the missing output attributes. and will address them as far as possible in #154
