### ISSUE TITLE
Schema conformance validation appears to be not reliable

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#98]
`recommendedDisplayRGBValue` is lower case in the schema

https://github.com/QIICR/dcmqi/blob/master/doc/seg-schema.json#L162

and upper case in this instantiation

https://github.com/QIICR/dcmqi/blob/master/doc/bmmr-example.json#L34

but the dashboard is green!

**Comment by fedorov** [comment]
It also didn't catch inconsistency that schema required RGB array to be of integers, but instead it was of strings.

**Comment by che85** [comment]
Let me check that. I might have an idea about what's causing it

**Comment by che85** [comment]
I think my idea is correct:

ajv does not know, that RecommendedDisplayRGBValue is recommendedDisplayRGBValue. It treats RecommendedDisplayRGBValue as an additional attribute and that's also why it doesn't check for the right types in the rgb array. When I try that locally on my machine and renaming it correctly, I get the following correct error output:

```
doc/bmmr-example.json invalid
[ { keyword: 'type',
    dataPath: '.segmentAttributes[0][0].recommendedDisplayRGBValue[0]',
    schemaPath: 'https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/RGB/items/type',
    params: { type: 'integer' },
    message: 'should be integer' },
  { keyword: 'type',
    dataPath: '.segmentAttributes[0][0].recommendedDisplayRGBValue[1]',
    schemaPath: 'https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/RGB/items/type',
    params: { type: 'integer' },
    message: 'should be integer' },
  { keyword: 'type',
    dataPath: '.segmentAttributes[0][0].recommendedDisplayRGBValue[2]',
    schemaPath: 'https://raw.githubusercontent.com/qiicr/dcmqi/master/doc/common-schema.json#/definitions/RGB/items/type',
    params: { type: 'integer' },
    message: 'should be integer' } ]
```

I will check if there is any option to take care of that

**Comment by fedorov** [comment]
Great! Sounds like you are on the right track!

**Comment by che85** [comment]
We should use "additionalProperties": false 

Then I get the following output:

```
doc/bmmr-example.json invalid
[ { keyword: 'additionalProperties',
    dataPath: '.segmentAttributes[0][0]',
    schemaPath: '#/properties/segmentAttributes/items/items/additionalProperties',
    params: { additionalProperty: 'RecommendedDisplayRGBValue' },
    message: 'should NOT have additional properties' } ]
```
